[svn-r28859] Merge of r28762, 28770-82, 28791-28806, 28816-28836, 28857 from revise_chunks.
This is basically all the revise_chunks changes since alpha0
aside from the v2 B-tree changes that cause SWMR to fail.

This merge should also bring the alpha branch in sync with
the trunk.

Tested on: 64-bit Ubuntu 15.10 (Linux 4.2.0 x86_64) gcc 5.2.1
           autotools serial w/ C++ and Fortran
           autotools parallel w/ Fortran (MPICH 3.1.4)
           cmake serial (cmakehdf5) w/ C++ and Fortran

diff --git a/bin/cmakehdf5 b/bin/cmakehdf5
--- a/bin/cmakehdf5
+++ b/bin/cmakehdf5
@@ -124,12 +124,12 @@ STEP()
 
     echo "$banner" with output saved in $logfile
     (TIMESTAMP; nerror=0 ;
-  echo "eval $command"
-  eval $command || nerror=1 ;
-  TIMESTAMP; exit $nerror) < /dev/null > "$logfile" 2>&1
+	echo "eval $command"
+	eval $command || nerror=1 ;
+	TIMESTAMP; exit $nerror) < /dev/null > "$logfile" 2>&1
     if [ $? -ne 0 ]; then
-  echo "error in '$banner'.  $progname aborted."
-  exit 1
+	echo "error in '$banner'.  $progname aborted."
+	exit 1
     fi
 }
 
@@ -143,26 +143,30 @@ INSTALL_HDF5()
 {
     myos="`uname -s`"
     case "$myos" in
-  Linux)
-      install_file=./HDF5-${version}-Linux.sh
-      $install_file  --skip-license $*
-      ;;
-  Darwin)		# Mac OSX DMG file
-      install_file=HDF5-${version}-Darwin.dmg
-      test -d hdf5 || mkdir hdf5
-      basename=`basename $install_file .dmg`
-      # mount the DMG file as /Volumes/$basename
-      # echo 'Y' as yes for license.
-      echo Y | hdiutil mount $install_file
-      # copy the contents to the install location
-      cp -R "/Volumes/$basename/HDF_Group" hdf5
-      # unmount the DMG file
-      hdiutil unmount /Volumes/$basename
-      ;;
-  *) 		# unknown/unsupported OS.
-      echo "INSTALL_HDF5: Error--unknown/unsupported OS($myos)"
-      return 1
-      ;;
+	Linux)
+	    install_file=./HDF5-${version}-Linux.sh
+	    $install_file  --skip-license $*
+	    ;;
+	Darwin)		# Mac OSX DMG file
+	    # These steps were a kludge. Need proper support from Cmake engineering.
+	    echo Darwin install step needs proper implementation. Quit.
+	    return 1
+	    #
+	    install_file=HDF5-${version}-Darwin.dmg
+	    test -d hdf5 || mkdir hdf5
+	    basename=`basename $install_file .dmg`
+	    # mount the DMG file as /Volumes/$basename
+	    # echo 'Y' as yes for license.
+	    echo Y | hdiutil mount $install_file
+	    # copy the contents to the install location
+	    cp -R "/Volumes/$basename/HDF_Group" hdf5
+	    # unmount the DMG file
+	    hdiutil unmount /Volumes/$basename
+	    ;;
+	*) 		# unknown/unsupported OS.
+	    echo "INSTALL_HDF5: Error--unknown/unsupported OS($myos)"
+	    return 1
+	    ;;
     esac
 }
 
@@ -172,14 +176,14 @@ INSTALL_HDF5()
 DUMP_LOGFILE()
 {
     for x in $*; do
-  if [ -f $x ]; then
-      echo "=================================="
-      echo "Dumping $x"
-      echo "=================================="
-      cat $x
-      echo "==== END $x ====="
-      echo
-  fi
+	if [ -f $x ]; then
+	    echo "=================================="
+	    echo "Dumping $x"
+	    echo "=================================="
+	    cat $x
+	    echo "==== END $x ====="
+	    echo
+	fi
     done
 }
 
@@ -207,84 +211,84 @@ fi
 # tools		Build tools
 while [ $# -gt 0 ]; do
     case "$1" in
-  --enable-fortran)
-      build_fortran=-DHDF5_BUILD_FORTRAN:BOOL=ON
-      ;;
-  --disable-fortran)
-      build_fortran=-DHDF5_BUILD_FORTRAN:BOOL=OFF
-      ;;
-  --enable-cxx)
-      build_cpp_lib=-DHDF5_BUILD_CPP_LIB:BOOL=ON
-      ;;
-  --disable-cxx)
-      build_cpp_lib=-DHDF5_BUILD_CPP_LIB:BOOL=OFF
-      ;;
-  --enable-hl)
-      build_hl_lib=-DHDF5_BUILD_HL_LIB:BOOL=ON
-      ;;
-  --disable-hl)
-      build_hl_lib=-DHDF5_BUILD_HL_LIB:BOOL=OFF
-      ;;
-  --enable-shared)
-      shared_lib=-DBUILD_SHARED_LIBS:BOOL=ON
-      ;;
-  --disable-shared)
-      shared_lib=-DBUILD_SHARED_LIBS:BOOL=OFF
-      ;;
-  --enable-tools)
-      build_tools=-DHDF5_BUILD_TOOLS:BOOL=ON
-      ;;
-  --disable-tools)
-      build_tools=-DHDF5_BUILD_TOOLS:BOOL=OFF
-      ;;
-  --enable-testing)
-      build_testing=-DBUILD_TESTING:BOOL=ON
-      ;;
-  --disable-testing)
-      build_testing=-DBUILD_TESTING:BOOL=OFF
-      ;;
-  --with-zlib)
-      with_zlib=-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON
-      ;;
-  --with-zlib=*)
-      xarg=`echo $1 | cut -d= -f2-`
-      with_zlib="-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON -DZLIB_ROOT=$xarg"
-      ;;
-  --without-zlib)
-      with_zlib=-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF
-      ;;
-  --with-szlib)
-      with_szlib=-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON
-      szlib_path=""	# szlib is in default paths
-      ;;
-  --with-szlib=*)
-      xarg=`echo $1 | cut -d= -f2-`
-      with_szlib="-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON"
-      szlib_path="SZIP_INSTALL=$xarg"
-      ;;
-  --without-szlib)
-      with_szlib=-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF
-      szlib_path=""	# reset the path
-      ;;
-  --njobs=*)
-      njobs=`echo $1 | cut -d= -f2-`
-      ;;
-  --enable-verbose)
-      vflag=1
-      ;;
-  --disable-verbose)
-      vflag=0
-      ;;
-  --help)
-      # print the detail help page and exit
-      HELP
-      exit 0
-      ;;
-  *)
-      echo "Unknown options: $1"
-      HELP
-      exit 1
-      ;;
+	--enable-fortran)
+	    build_fortran=-DHDF5_BUILD_FORTRAN:BOOL=ON
+	    ;;
+	--disable-fortran)
+	    build_fortran=-DHDF5_BUILD_FORTRAN:BOOL=OFF
+	    ;;
+	--enable-cxx)
+	    build_cpp_lib=-DHDF5_BUILD_CPP_LIB:BOOL=ON
+	    ;;
+	--disable-cxx)
+	    build_cpp_lib=-DHDF5_BUILD_CPP_LIB:BOOL=OFF
+	    ;;
+	--enable-hl)
+	    build_hl_lib=-DHDF5_BUILD_HL_LIB:BOOL=ON
+	    ;;
+	--disable-hl)
+	    build_hl_lib=-DHDF5_BUILD_HL_LIB:BOOL=OFF
+	    ;;
+	--enable-shared)
+	    shared_lib=-DBUILD_SHARED_LIBS:BOOL=ON
+	    ;;
+	--disable-shared)
+	    shared_lib=-DBUILD_SHARED_LIBS:BOOL=OFF
+	    ;;
+	--enable-tools)
+	    build_tools=-DHDF5_BUILD_TOOLS:BOOL=ON
+	    ;;
+	--disable-tools)
+	    build_tools=-DHDF5_BUILD_TOOLS:BOOL=OFF
+	    ;;
+	--enable-testing)
+	    build_testing=-DBUILD_TESTING:BOOL=ON
+	    ;;
+	--disable-testing)
+	    build_testing=-DBUILD_TESTING:BOOL=OFF
+	    ;;
+	--with-zlib)
+	    with_zlib=-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON
+	    ;;
+	--with-zlib=*)
+	    xarg=`echo $1 | cut -d= -f2-`
+	    with_zlib="-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON -DZLIB_ROOT=$xarg"
+	    ;;
+	--without-zlib)
+	    with_zlib=-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF
+	    ;;
+	--with-szlib)
+	    with_szlib=-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON
+	    szlib_path=""	# szlib is in default paths
+	    ;;
+	--with-szlib=*)
+	    xarg=`echo $1 | cut -d= -f2-`
+	    with_szlib="-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON"
+	    szlib_path="SZIP_INSTALL=$xarg"
+	    ;;
+	--without-szlib)
+	    with_szlib=-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF
+	    szlib_path=""	# reset the path
+	    ;;
+	--njobs=*)
+	    njobs=`echo $1 | cut -d= -f2-`
+	    ;;
+	--enable-verbose)
+	    vflag=1
+	    ;;
+	--disable-verbose)
+	    vflag=0
+	    ;;
+	--help)
+	    # print the detail help page and exit
+	    HELP
+	    exit 0
+	    ;;
+	*)
+	    echo "Unknown options: $1"
+	    HELP
+	    exit 1
+	    ;;
     esac
     shift
 done
@@ -313,8 +317,8 @@ fi
 
 # setup output of all the log files if verbose is on upon exit
 trap \
-"if [ $vflag -ne 0 ]; then DUMP_LOGFILE \$configlog \$makelog \$testlog \$packlog \$installlog; fi" \
-0
+    "if [ $vflag -ne 0 ]; then DUMP_LOGFILE \$configlog \$makelog \$testlog \$packlog \$installlog; fi" \
+    0
 
 echo Running Cmake for HDF5-${version} ...
 #      4. Configure the C library, tools and tests with this command:
@@ -343,8 +347,13 @@ STEP "Test the library and tools..." "ctest . -C Release $njobs" $testlog
 #      7. Create an install image with this command:
 STEP "Create an install image..." "cpack -C Release CPackConfig.cmake" $packlog
 
+# The implementation of installation is imcomplete (only works for linux).
+# Screen it out for now till it is completed.
+if false; then
 #      8. Install with this command:
 STEP "Install..." "INSTALL_HDF5" $installlog
+fi
+
 # save the last exit code
 exit_code=$?
 
