[svn-r12528] Added User-Defined links to the library.
Users can create external links using H5L_create_external().  These links
point to an object in another HDF5 file.  Users can alter the behavior of
external links or create new kinds of links by registering callbacks
using the H5L interface.

Added tests, tools support, etc.

Also a number of other, minor changes have been made (some restructuring of
the H5L interface, for instance).

Additional documentation and examples are forthcoming.

diff --git a/bin/reconfigure b/bin/reconfigure
--- a/bin/reconfigure
+++ b/bin/reconfigure
@@ -120,4 +120,11 @@ echo
 echo "    Running trace script:"
 bin/trace src/H5*.c || exit 1
 
+# Run make_error
+# make_error automatically generates the H5E headers that create error message
+# types for HDF5.
+echo
+echo "    Running error generation script:"
+bin/make_err src/H5err.txt || exit 1
+
 exit 0
