Update examples version because of HDFFV-11269

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -39,29 +39,29 @@ USAGE()
 {
 cat << EOF
 Usage: $0 -d <dir> [--docver BRANCHNAME] [-h] [--nocheck] [--private] <methods> ...
-   -d DIR	The name of the directory where the releas(es) should be
+   -d DIR   The name of the directory where the releas(es) should be
                 placed.
    --docver BRANCHNAME  This is added for 1.8 and beyond to get the correct
                         version of documentation files from the hdf5docs
                         repository.  BRANCHNAME for v1.8 should be hdf5_1_8.
    -h           print the help page.
-   --nocheck	Ignore errors in MANIFEST file.
-   --private	Make a private release with today's date in version information.
-         
+   --nocheck    Ignore errors in MANIFEST file.
+   --private    Make a private release with today's date in version information.
+
 This must be run at the top level of the source directory.
 The other command-line options are the names of the programs to use
 for compressing the resulting tar archive (if none are given then
 "tar" is assumed):
 
-    tar		-- use tar and don't do any compressing.
-    gzip	-- use gzip with "-9" and append ".gz" to the output name.
-    cmake-tgz   -- create a tar file using the gzip default level with a build-unix.sh 
+    tar         -- use tar and don't do any compressing.
+    gzip        -- use gzip with "-9" and append ".gz" to the output name.
+    bzip2       -- use bzip2 with "-9" and append ".bz2" to the output name.
+    zip         -- convert all text files to DOS style and form a zip file for Windows use.
+    cmake-tgz   -- create a tar file using the gzip default level with a build-unix.sh
                    command file and all other CMake files needed to build HDF5 source
                    using CMake on unix machines.
-    bzip2       -- use bzip2 with "-9" and append ".bz2" to the output name.
-    zip		-- convert all text files to DOS style and form a zip file for Windows use.
     cmake-zip   -- convert all text files to DOS style and create a zip file inluding cmake
-                   scripts and .bat files to build HDF5 source using CMake on Windows. 
+                   scripts and .bat files to build HDF5 source using CMake on Windows.
     doc         -- produce the latest doc tree in addition to the archive.
 
 An md5 checksum is produced for each archive created and stored in the md5 file.
@@ -114,8 +114,8 @@ EOF
 tar2zip()
 {
     if [ $# -ne 3 ]; then
-	echo "usage: tar2zip <tarfilename> <zipfilename>"
-	return 1
+        echo "usage: tar2zip <tarfilename> <zipfilename>"
+        return 1
     fi
     ztmpdir=/tmp/ztmpdir$$
     mkdir -p $ztmpdir
@@ -127,23 +127,23 @@ tar2zip()
     (cd $ztmpdir; tar xf -) < $tarfile
     # sanity check
     if [ ! -d $ztmpdir/$version ]; then
-	echo "untar did not create $ztmpdir/$version source dir"
-	# cleanup
-	rm -rf $ztmpdir
-	return 1
+        echo "untar did not create $ztmpdir/$version source dir"
+        # cleanup
+        rm -rf $ztmpdir
+        return 1
     fi
     # step 2: convert text files
     # There maybe a simpler way to do this.
     # options used in unix2dos:
-    # -k   Keep the date stamp 
+    # -k   Keep the date stamp
     # -q   quiet mode
     # grep redirect output to /dev/null because -q or -s are not portable.
     find $ztmpdir/$version | \
-	while read inf; do \
-	    if file $inf | grep "$inf\: .*text" > /dev/null 2>&1 ; then \
-		unix2dos -q -k $inf; \
-	    fi\
-	done
+        while read inf; do \
+            if file $inf | grep "$inf\: .*text" > /dev/null 2>&1 ; then \
+                unix2dos -q -k $inf; \
+            fi\
+        done
     # step 3: make zipball
     # -9 maximum compression
     # -y Store symbolic links as such in the zip archive
@@ -194,8 +194,8 @@ tar2zip()
 tar2cmakezip()
 {
     if [ $# -ne 3 ]; then
-	echo "usage: tar2cmakezip <tarfilename> <zipfilename>"
-	return 1
+        echo "usage: tar2cmakezip <tarfilename> <zipfilename>"
+        return 1
     fi
     cmziptmpdir=/tmp/cmziptmpdir$$
     cmziptmpsubdir=$cmziptmpdir/CMake-$HDF5_VERS
@@ -208,10 +208,10 @@ tar2cmakezip()
     (cd $cmziptmpsubdir; tar xf -) < $tarfile
     # sanity check
     if [ ! -d $cmziptmpsubdir/$version ]; then
-	echo "untar did not create $cmziptmpsubdir/$version source dir"
-	# cleanup
-	rm -rf $cmziptmpdir
-	return 1
+        echo "untar did not create $cmziptmpsubdir/$version source dir"
+        # cleanup
+        rm -rf $cmziptmpdir
+        return 1
     fi
 
     # step 2: add batch file for building CMake on window
@@ -221,11 +221,14 @@ tar2cmakezip()
     (cd $cmziptmpsubdir; echo "ctest -S HDF5config.cmake,BUILD_GENERATOR=VS201564 -C Release -V -O hdf5.log" > build-VS2015-64.bat; chmod 755 build-VS2015-64.bat)
     (cd $cmziptmpsubdir; echo "ctest -S HDF5config.cmake,BUILD_GENERATOR=VS2017 -C Release -V -O hdf5.log" > build-VS2017-32.bat; chmod 755 build-VS2017-32.bat)
     (cd $cmziptmpsubdir; echo "ctest -S HDF5config.cmake,BUILD_GENERATOR=VS201764 -C Release -V -O hdf5.log" > build-VS2017-64.bat; chmod 755 build-VS2017-64.bat)
+    (cd $cmziptmpsubdir; echo "ctest -S HDF5config.cmake,BUILD_GENERATOR=VS2019 -C Release -V -O hdf5.log" > build-VS2019-32.bat; chmod 755 build-VS2019-32.bat)
+    (cd $cmziptmpsubdir; echo "ctest -S HDF5config.cmake,BUILD_GENERATOR=VS201964 -C Release -V -O hdf5.log" > build-VS2019-64.bat; chmod 755 build-VS2019-64.bat)
 
     # step 3: add LIBAEC.tar.gz, ZLib.tar.gz and cmake files
     cp /mnt/scr1/pre-release/hdf5/CMake/LIBAEC.tar.gz $cmziptmpsubdir
     cp /mnt/scr1/pre-release/hdf5/CMake/ZLib.tar.gz $cmziptmpsubdir
-    cp /mnt/scr1/pre-release/hdf5/CMake/HDF5Examples-0.2.11-Source.tar.gz $cmziptmpsubdir
+    cp /mnt/scr1/pre-release/hdf5/CMake/HDF5Examples-1.8.14-Source.tar.gz $cmziptmpsubdir
+    cp /mnt/scr1/pre-release/hdf5/CMake/hdf5_plugins-1.8.22.zip $cmziptmpsubdir
     cp $cmziptmpsubdir/$version/config/cmake/scripts/CTestScript.cmake $cmziptmpsubdir
     cp $cmziptmpsubdir/$version/config/cmake/scripts/HDF5config.cmake $cmziptmpsubdir
     cp $cmziptmpsubdir/$version/config/cmake/scripts/HDF5options.cmake $cmziptmpsubdir
@@ -233,15 +236,16 @@ tar2cmakezip()
     # step 4: convert text files
     # There maybe a simpler way to do this.
     # options used in unix2dos:
-    # -k   Keep the date stamp 
+    # -k   Keep the date stamp
     # -q   quiet mode
     # grep redirect output to /dev/null because -q or -s are not portable.
     find $cmziptmpsubdir/$version | \
-	while read inf; do \
-	    if file $inf | grep "$inf\: .*text" > /dev/null 2>&1 ; then \
-		unix2dos -q -k $inf; \
-	    fi\
-	done
+        while read inf; do \
+            if file $inf | grep "$inf\: .*text" > /dev/null 2>&1 ; then \
+                unix2dos -q -k $inf; \
+            fi\
+        done
+
     # step 3: make zipball
     # -9 maximum compression
     # -y Store symbolic links as such in the zip archive
@@ -255,7 +259,7 @@ tar2cmakezip()
 }
 
 # Function name: tar2cmaketgz
-# Convert the release tarball to a Windows zipball with files to run CMake build.
+# Convert the release tarball to a gzipped tar file with files to run CMake build.
 #
 # Programmer: Larry Knox
 # Creation date: 2017-02-20
@@ -292,8 +296,8 @@ tar2cmakezip()
 tar2cmaketgz()
 {
     if [ $# -ne 3 ]; then
-	echo "usage: tar2cmaketgz <tarfilename> <tgzfilename>"
-	return 1
+        echo "usage: tar2cmaketgz <tarfilename> <tgzfilename>"
+        return 1
     fi
     cmgztmpdir=/tmp/cmgztmpdir$$
     cmgztmpsubdir=$cmgztmpdir/CMake-$HDF5_VERS
@@ -306,10 +310,10 @@ tar2cmaketgz()
     (cd $cmgztmpsubdir; tar xf -) < $tarfile
     # sanity check
     if [ ! -d $cmgztmpsubdir/$version ]; then
-	echo "untar did not create $cmgztmpsubdir/$version source dir"
-	# cleanup
-	rm -rf $cmgztmpdir
-	return 1
+        echo "untar did not create $cmgztmpsubdir/$version source dir"
+        # cleanup
+        rm -rf $cmgztmpdir
+        return 1
     fi
 
 
@@ -319,12 +323,32 @@ tar2cmaketgz()
     # step 3: add LIBAEC.tar.gz, ZLib.tar.gz and cmake files
     cp /mnt/scr1/pre-release/hdf5/CMake/LIBAEC.tar.gz $cmgztmpsubdir
     cp /mnt/scr1/pre-release/hdf5/CMake/ZLib.tar.gz $cmgztmpsubdir
-    cp /mnt/scr1/pre-release/hdf5/CMake/HDF5Examples-0.2.11-Source.tar.gz $cmgztmpsubdir
+    cp /mnt/scr1/pre-release/hdf5/CMake/HDF5Examples-1.8.14-Source.tar.gz $cmgztmpsubdir
+    cp /mnt/scr1/pre-release/hdf5/CMake/hdf5_plugins-1.8.22.tar.gz $cmgztmpsubdir
     cp $cmgztmpsubdir/$version/config/cmake/scripts/CTestScript.cmake $cmgztmpsubdir
     cp $cmgztmpsubdir/$version/config/cmake/scripts/HDF5config.cmake $cmgztmpsubdir
     cp $cmgztmpsubdir/$version/config/cmake/scripts/HDF5options.cmake $cmgztmpsubdir
-    tar czf $DEST/CMake-$HDF5_VERS.tar.gz -C $cmgztmpdir . || exit 1 
-                 
+    tar czf $DEST/CMake-$HDF5_VERS.tar.gz -C $cmgztmpdir . || exit 1
+
+    # cleanup
+    rm -rf $cmgztmpdir
+    return 1
+    fi
+
+
+    # step 2: add build-unix.sh script
+    (cd $cmgztmpsubdir; echo "ctest -S HDF5config.cmake,BUILD_GENERATOR=Unix -C Release -V -O hdf5.log" > build-unix.sh; chmod 755 build-unix.sh)
+
+    # step 3: add LIBAEC.tar.gz, ZLib.tar.gz and cmake files
+    cp /mnt/scr1/pre-release/hdf5/CMake/LIBAEC.tar.gz $cmgztmpsubdir
+    cp /mnt/scr1/pre-release/hdf5/CMake/ZLib.tar.gz $cmgztmpsubdir
+    cp /mnt/scr1/pre-release/hdf5/CMake/HDF5Examples-1.8.14-Source.tar.gz $cmgztmpsubdir
+    cp /mnt/scr1/pre-release/hdf5/CMake/hdf5_plugins-1.8.22.tar.gz $cmgztmpsubdir
+    cp $cmgztmpsubdir/$version/config/cmake/scripts/CTestScript.cmake $cmgztmpsubdir
+    cp $cmgztmpsubdir/$version/config/cmake/scripts/HDF5config.cmake $cmgztmpsubdir
+    cp $cmgztmpsubdir/$version/config/cmake/scripts/HDF5options.cmake $cmgztmpsubdir
+    tar czf $DEST/CMake-$HDF5_VERS.tar.gz -C $cmgztmpdir . || exit 1
+
     # cleanup
     rm -rf $cmgztmpdir
 }
@@ -346,7 +370,7 @@ check=yes
 release_date=`date +%F`
 today=`date +%Y%m%d`
 pmode='no'
-tmpdir="../#release_tmp.$$"	# tmp work directory
+tmpdir="../#release_tmp.$$"     # tmp work directory
 DOC_URL=https://git@bitbucket.hdfgroup.org/scm/hdffv/hdf5doc.git
 CPPLUS_RM_NAME=cpplus_RM
 MAINT_MODE_ENABLED=""
@@ -363,11 +387,11 @@ fi
 RESTORE_VERSION()
 {
     if [ X-${VERS_OLD} != X- ]; then
-	echo restoring version information back to $VERS_OLD
-	rm -f config/lt_vers.am
-	cp $tmpdir/lt_vers.am config/lt_vers.am
-	bin/h5vers -s $VERS_OLD
-	VERS_OLD=
+        echo restoring version information back to $VERS_OLD
+        rm -f config/lt_vers.am
+        cp $tmpdir/lt_vers.am config/lt_vers.am
+        bin/h5vers -s $VERS_OLD
+        VERS_OLD=
     fi
 }
 
@@ -377,32 +401,32 @@ while [ -n "$1" ]; do
     arg=$1
     shift
     case "$arg" in
-	-d)
-	    DEST=$1
-	    shift
-	    ;;
-	--nocheck)
-	    check=no
-	    ;;
-	-h)
-	    USAGE
-	    exit 0
-	    ;;
-	--private)
-	    pmode=yes
-	    ;;
+        -d)
+            DEST=$1
+            shift
+            ;;
+        --nocheck)
+            check=no
+            ;;
+        -h)
+            USAGE
+            exit 0
+            ;;
+        --private)
+            pmode=yes
+            ;;
         --docver)
             DOCVERSION=$1
             shift
             ;;
-	-*)
-	    echo "Unknown switch: $arg" 1>&2
-	    USAGE
-	    exit 1
-	    ;;
-	*)
-	    methods="$methods $arg"
-	    ;;
+        -*)
+            echo "Unknown switch: $arg" 1>&2
+            USAGE
+            exit 1
+            ;;
+        *)
+            methods="$methods $arg"
+            ;;
     esac
 done
 
@@ -451,7 +475,7 @@ if [ "X$fail" = "Xyes" ]; then
     if [ $check = yes ]; then
         exit 1
     else
-	echo "Continuing anyway..."
+        echo "Continuing anyway..."
     fi
 fi
 
@@ -485,7 +509,7 @@ test "$verbose" && echo "   Running tar..." 1>&2
 ( \
     cd $tmpdir; \
     tar cf $HDF5_VERS.tar $HDF5_VERS/Makefile \
-	`sed 's/^\.\//hdf5-'$VERS'\//' $MANIFEST` || exit 1 \
+    `sed 's/^\.\//hdf5-'$VERS'\//' $MANIFEST` || exit 1 \
 )
 
 # Compress
@@ -493,56 +517,56 @@ MD5file=$HDF5_VERS.md5
 cp /dev/null $DEST/$MD5file
 for comp in $methods; do
     case $comp in
-	tar)
-	    cp -p $tmpdir/$HDF5_VERS.tar $DEST/$HDF5_VERS.tar
-	    (cd $DEST; md5sum $HDF5_VERS.tar >> $MD5file) 
-	    ;;
-	gzip)
-	    test "$verbose" && echo "   Running gzip..." 1>&2
-	    gzip -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.gz
-	    (cd $DEST; md5sum $HDF5_VERS.tar.gz >> $MD5file) 
-	    ;;
-        cmake-tgz)
-	    test "$verbose" && echo "   Creating CMake tar.gz file..." 1>&2
-	    tar2cmaketgz $HDF5_VERS $tmpdir/$HDF5_VERS.tar $DEST/CMake-$HDF5_VERS.tar.gz 1>&2
-	    (cd $DEST; md5sum CMake-$HDF5_VERS.tar.gz >> $MD5file) 
+        tar)
+            cp -p $tmpdir/$HDF5_VERS.tar $DEST/$HDF5_VERS.tar
+            (cd $DEST; md5sum $HDF5_VERS.tar >> $MD5file)
             ;;
-	bzip2)
-	    test "$verbose" && echo "   Running bzip2..." 1>&2
-	    bzip2 -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.bz2
-	    (cd $DEST; md5sum $HDF5_VERS.tar.bz2 >> $MD5file) 
-	    ;;
-	zip)
-	    test "$verbose" && echo "   Creating zip ball..." 1>&2
-	    tar2zip $HDF5_VERS $tmpdir/$HDF5_VERS.tar $DEST/$HDF5_VERS.zip 1>&2
-	    (cd $DEST; md5sum $HDF5_VERS.zip >> $MD5file) 
-	    ;;
+        gzip)
+            test "$verbose" && echo "   Running gzip..." 1>&2
+            gzip -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.gz
+            (cd $DEST; md5sum $HDF5_VERS.tar.gz >> $MD5file)
+            ;;
+        cmake-tgz)
+            test "$verbose" && echo "   Creating CMake tar.gz file..." 1>&2
+            tar2cmaketgz $HDF5_VERS $tmpdir/$HDF5_VERS.tar $DEST/CMake-$HDF5_VERS.tar.gz 1>&2
+            (cd $DEST; md5sum CMake-$HDF5_VERS.tar.gz >> $MD5file)
+            ;;
+        bzip2)
+            test "$verbose" && echo "   Running bzip2..." 1>&2
+            bzip2 -9 <$tmpdir/$HDF5_VERS.tar >$DEST/$HDF5_VERS.tar.bz2
+            (cd $DEST; md5sum $HDF5_VERS.tar.bz2 >> $MD5file)
+            ;;
+        zip)
+            test "$verbose" && echo "   Creating zip ball..." 1>&2
+            tar2zip $HDF5_VERS $tmpdir/$HDF5_VERS.tar $DEST/$HDF5_VERS.zip 1>&2
+            (cd $DEST; md5sum $HDF5_VERS.zip >> $MD5file)
+            ;;
         cmake-zip)
             test "$verbose" && echo "   Creating CMake-zip ball..." 1>&2
             tar2cmakezip $HDF5_VERS $tmpdir/$HDF5_VERS.tar $DEST/CMake-$HDF5_VERS.zip 1>&2
             (cd $DEST; md5sum CMake-$HDF5_VERS.zip >> $MD5file)
             ;;
-	doc)
+        doc)
             if [ "${DOCVERSION}" = "" ]; then
                 DOCVERSION=master
             fi
-	    test "$verbose" && echo "   Creating docs..." 1>&2
-	    # Check out docs from git repo
-	    (cd $tmpdir; git clone -q $DOC_URL ${DOCVERSION} > /dev/null) || exit 1
+            test "$verbose" && echo "   Creating docs..." 1>&2
+            # Check out docs from git repo
+            (cd $tmpdir; git clone -q $DOC_URL ${DOCVERSION} > /dev/null) || exit 1
             # Create doxygen C++ RM
-	    (cd c++/src && doxygen cpp_doc_config > /dev/null ) || exit 1
-	    # Replace version of C++ RM with just-created version
-	    rm -rf $tmpdir/${DOCVERSION}/html/$CPPLUS_RM_NAME || exit 1
-	    mv c++/src/$CPPLUS_RM_NAME $tmpdir/${DOCVERSION}/html/$CPPLUS_RM_NAME || exit 1
+            (cd c++/src && doxygen cpp_doc_config > /dev/null ) || exit 1
+            # Replace version of C++ RM with just-created version
+            rm -rf $tmpdir/${DOCVERSION}/html/$CPPLUS_RM_NAME || exit 1
+            mv c++/src/$CPPLUS_RM_NAME $tmpdir/${DOCVERSION}/html/$CPPLUS_RM_NAME || exit 1
             # Compress the docs and move them to the release area
-	    mv $tmpdir/${DOCVERSION} $tmpdir/${HDF5_VERS}_docs || exit 1
-	    (cd $tmpdir && tar cf ${HDF5_VERS}_docs.tar ${HDF5_VERS}_docs) || exit 1
-	    mv $tmpdir/${HDF5_VERS}_docs.tar $DEST || exit 1
-	    ;;
-	*)
-	    echo "***Error*** Unknown method $comp"
-	    exit 1
-	    ;;
+            mv $tmpdir/${DOCVERSION} $tmpdir/${HDF5_VERS}_docs || exit 1
+            (cd $tmpdir && tar cf ${HDF5_VERS}_docs.tar ${HDF5_VERS}_docs) || exit 1
+            mv $tmpdir/${HDF5_VERS}_docs.tar $DEST || exit 1
+            ;;
+        *)
+            echo "***Error*** Unknown method $comp"
+            exit 1
+            ;;
     esac
 done
 
