Fix for HDFFV-10659: The library abort with "infinite loop closing library" after deleting attributes in densed storage. The fix: When deleting attribute nodes from the name index v2 B-tree, if an attribute is found in the intermediate B-tree nodes, which may be merged/redistributed in the process, we need to free the dynamically allocated spaces for the intermediate decoded attribute.

diff --git a/test/testabort_fail.sh.in b/test/testabort_fail.sh.in
--- a/test/testabort_fail.sh.in
+++ b/test/testabort_fail.sh.in
@@ -13,6 +13,9 @@
 #
 # Test to verify that the assertion/abort failure is fixed when the application
 # does not close the file. (See HDFFV-10160)
+#
+# Test to verify that the infinite loop closing library/abort failure is fixed 
+# when the application creates and removes densed attributes (See HDFFV-10659)
 
 srcdir=@srcdir@
 
@@ -20,22 +23,44 @@ nerrors=0
 
 ##############################################################################
 ##############################################################################
-###			  T H E   T E S T                                              ###
+###			  T H E   T E S T S                                            ###
 ##############################################################################
 ##############################################################################
-
+#
+#
 echo "Testing file not closed assertion/abort failure"
 TEST_NAME=filenotclosed     # The test name
-TEST_BIN=`pwd`/$TEST_NAME 	# The path of the test binary
+TEST_BIN=`pwd`/$TEST_NAME   # The path of the test binary
 #
 # Run the test
-#$RUNSERIAL $TEST_BIN >/dev/null 2>&1 
-$RUNSERIAL $TEST_BIN 2>&1 
+$RUNSERIAL $TEST_BIN >/dev/null 2>&1 
 exitcode=$?
 if [ $exitcode -eq 0 ]; then
     echo "Test PASSED"
 else
+    echo "Test FAILED"
  	nerrors="`expr $nerrors + 1`"
-	echo "***Error encountered***"
 fi
-exit $nerrors
+#
+#
+echo "Testing infinite loop closing library/abort failure"
+TEST_NAME=del_many_dense_attrs  # The test name
+TEST_BIN=`pwd`/$TEST_NAME 	    # The path of the test binary
+# Run the test
+$RUNSERIAL $TEST_BIN >/dev/null 2>&1 
+exitcode=$?
+if [ $exitcode -eq 0 ]; then
+    echo "Test PASSED"
+else
+    echo "Test FAILED"
+ 	nerrors="`expr $nerrors + 1`"
+fi
+#
+#
+if test $nerrors -eq 0 ; then
+    echo "All tests for abort failure passed."
+    exit 0
+else
+    echo "Tests for abort failure failed with $nerrors errors."
+    exit 1
+fi
