[svn-r17054] merge 17052 from trunk Add a run to the h5repack shell script to read a family file The file used for input is located in the common source tools for testfiles, in tools/testfiles Modified the h5repack shell script to read files from this location (h5repack reads its input files from a dedicated testfiles location in h5repack/testfiles) Changed the h5diff open file call to use h5tools_fopen, so that it can open all file drivers
Tested: linux

diff --git a/tools/h5repack/h5repack.sh.in b/tools/h5repack/h5repack.sh.in
--- a/tools/h5repack/h5repack.sh.in
+++ b/tools/h5repack/h5repack.sh.in
@@ -51,6 +51,8 @@ FILE9=h5repack_shuffle.h5
 FILE10=h5repack_fletcher.h5
 FILE11=h5repack_filters.h5
 
+FILE16=tfamily%05d.h5           # located in common testfiles folder
+
 
 nerrors=0
 verbose=yes
@@ -115,6 +117,38 @@ TOOLTEST()
     TESTING $H5REPACK $@
 
     infile=$srcdir/testfiles/$1
+    path=`pwd`
+    outfile=$path/out.$1
+    shift
+    if [ "`uname -s`" = "TFLOPS O/S" ]; then
+     $RUNSERIAL $H5REPACK_BIN $@ $infile $outfile
+    else
+     $RUNSERIAL $H5REPACK_BIN "$@" $infile $outfile
+    fi
+
+    RET=$?
+    if [ $RET != 0 ] ; then
+     echo "*FAILED*"
+     nerrors="`expr $nerrors + 1`"
+    else
+     echo " PASSED"
+     DIFFTEST $infile $outfile
+    fi
+    rm -f $outfile
+}
+
+
+# same as TOOLTEST, but it uses the common testfiles at $srcdir/../testfiles/
+# used to test the family driver, where these files reside
+#
+TOOLTEST1() 
+{
+    # Run test.
+    # Tflops interprets "$@" as "" when no parameter is given (e.g., the
+    # case of missing file name).  Changed it to use $@ till Tflops fixes it.
+    TESTING $H5REPACK $@
+
+    infile=$srcdir/../testfiles/$1
     path=`pwd`
     outfile=$path/out.$1
     shift
@@ -399,6 +433,9 @@ TOOLTEST $arg
 
 # test for datum size > H5TOOLS_MALLOCSIZE
 TOOLTEST $FILE1 -f GZIP=1
+
+# tests family driver (file is located in common testfiles folder, uses TOOLTEST1)
+TOOLTEST1 $FILE16
 
 
 if test $nerrors -eq 0 ; then
