[svn-r15262] Description: 	Merge revisions 15037:15130 from trunk into metadata journaling branch
Tested on:
        FreeBSD/32 6.2 (duty) in debug mode
        FreeBSD/64 6.2 (liberty) w/C++ & FORTRAN, in debug mode
        Linux/32 2.6 (kagiso) w/PGI compilers, w/C++ & FORTRAN, w/threadsafe,
                                in debug mode
        Linux/64-amd64 2.6 (smirom) w/default API=1.6.x, w/C++ & FORTRAN,
                                in production mode
        Linux/64-ia64 2.6 (cobalt) w/Intel compilers, w/C++ & FORTRAN,
                                in production mode
        Solaris/32 2.10 (linew) w/deprecated symbols disabled, w/C++ & FORTRAN,
                                w/szip filter, in production mode
        Mac OS X/32 10.5.2 (amazon) in debug mode
        Linux/64-ia64 2.4 (tg-login3) w/parallel, w/FORTRAN, in production mode

diff --git a/tools/h5repack/h5repack.sh.in b/tools/h5repack/h5repack.sh.in
--- a/tools/h5repack/h5repack.sh.in
+++ b/tools/h5repack/h5repack.sh.in
@@ -137,6 +137,34 @@ TOOLTEST()
     rm -f $outfile
 }
 
+TOOLTEST0() 
+{
+    # Run test.
+    # Tflops interprets "$@" as "" when no parameter is given (e.g., the
+    # case of missing file name).  Changed it to use $@ till Tflops fixes it.
+    TESTING $H5REPACK $@
+
+    infile=$srcdir/../testfiles/$1
+    path=`pwd`
+    outfile=$path/out.$1
+    shift
+    if [ "`uname -s`" = "TFLOPS O/S" ]; then
+     $RUNSERIAL $H5REPACK_BIN -i $infile -o $outfile $@
+    else
+     $RUNSERIAL $H5REPACK_BIN -i $infile -o $outfile "$@"
+    fi
+
+    RET=$?
+    if [ $RET != 0 ] ; then
+     echo "*FAILED*"
+     nerrors="`expr $nerrors + 1`"
+    else
+     echo " PASSED"
+     DIFFTEST $infile $outfile
+    fi
+    rm -f $outfile
+}
+
 #
 # The tests
 # We use the files generated by h5repacktst
@@ -428,9 +456,16 @@ TOOLTEST $FILE4 -l dset_chunk:CHUNK=18x13
 TOOLTEST $FILE1 -n
 
 
-# long swtiches. use FILE4=h5repack_layout.h5 (no filters)
-
+# latest file format with long switches. use FILE4=h5repack_layout.h5 (no filters)
 arg="$FILE4 --layout CHUNK=20x10 --filter GZIP=1 --threshold=10 --native --latest --compact=8 --indexed=6 --ssize=8[:dtype]"
+if test $USE_FILTER_DEFLATE != "yes" ; then
+ SKIP $arg
+else
+ TOOLTEST $arg
+fi
+
+# latest file format with short switches. use FILE4=h5repack_layout.h5 (no filters)
+arg="$FILE4 -l CHUNK=20x10 -f GZIP=1 -m 10 -n -L -c 8 -d 6 -s 8[:dtype]"
 if test $USE_FILTER_DEFLATE != "yes" ; then
  SKIP $arg
 else
@@ -445,6 +480,15 @@ if test $USE_FILTER_DEFLATE != "yes" -o $USE_FILTER_SHUFFLE != "yes" ; then
 else
  TOOLTEST $arg
 fi
+
+# syntax of -i infile -o outfile
+# latest file format with short switches. use FILE4=h5repack_layout.h5 (no filters)
+arg="$FILE4 -l CHUNK=20x10 -f GZIP=1 -m 10 -n -L -c 8 -d 6 -s 8[:dtype]"
+if test $USE_FILTER_DEFLATE != "yes" ; then
+ SKIP $arg
+else
+ TOOLTEST0 $arg
+fi 
 
 
 if test $nerrors -eq 0 ; then
