[svn-r18984] Description: Fixed exit code (sometimes return code in Main) to follow the HDF5 standards.
Tested:
Tested in Dove-linux only since change is trivial and has passed in v1.8.

diff --git a/tools/h5ls/testh5ls.sh.in b/tools/h5ls/testh5ls.sh.in
--- a/tools/h5ls/testh5ls.sh.in
+++ b/tools/h5ls/testh5ls.sh.in
@@ -15,6 +15,10 @@
 #
 # Tests for the h5ls tool
 
+TESTNAME=h5ls
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 H5LS=h5ls               # The tool name
 H5LS_BIN=`pwd`/$H5LS    # The path of the tool binary
 
@@ -207,7 +211,9 @@ fi
 
 
 if test $nerrors -eq 0 ; then
-	echo "All h5ls tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
