[svn-r18175] Description: 	Bring r17986:18172 from trunk to revise_chunks branch.
Tested on:
        FreeBSD/32 6.3 (duty) in debug mode
        FreeBSD/64 6.3 (liberty) w/C++ & FORTRAN, in debug mode
        Linux/32 2.6 (jam) w/PGI compilers, w/default API=1.8.x,
                w/C++ & FORTRAN, w/threadsafe, in debug mode
        Linux/64-amd64 2.6 (amani) w/Intel compilers, w/default API=1.6.x,
                w/C++ & FORTRAN, in production mode
        Solaris/32 2.10 (linew) w/deprecated symbols disabled, w/C++ & FORTRAN,
                w/szip filter, in production mode
        Linux/64-ia64 2.6 (cobalt) w/Intel compilers, w/C++ & FORTRAN,
                in production mode
        Linux/64-ia64 2.4 (tg-login3) w/parallel, w/FORTRAN, in debug mode
        Linux/64-amd64 2.6 (abe) w/parallel, w/FORTRAN, in production mode

diff --git a/c++/examples/testh5c++.sh.in b/c++/examples/testh5c++.sh.in
--- a/c++/examples/testh5c++.sh.in
+++ b/c++/examples/testh5c++.sh.in
@@ -20,6 +20,10 @@
 #
 
 # Initializations
+TESTNAME=h5c++
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 # Where the tool is installed.
 prefix="${prefix:-@prefix@}"
 AR="@AR@"
@@ -30,7 +34,7 @@ H5TOOL_BIN="${prefix}/bin/${H5TOOL}"   # The path of the tool binary
 CMP='cmp -s'
 DIFF='diff -c'
 
-nerrors=0
+nerrors=$EXIT_SUCCESS
 verbose=yes
 
 # setup my machine information.
@@ -271,7 +275,9 @@ if test -z "$HDF5_NOCLEANUP"; then
 fi
 
 if test $nerrors -eq 0 ; then
-   echo "All $H5TOOL tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
diff --git a/examples/testh5cc.sh.in b/examples/testh5cc.sh.in
--- a/examples/testh5cc.sh.in
+++ b/examples/testh5cc.sh.in
@@ -24,6 +24,10 @@
 #
 
 # Initializations
+TESTNAME=h5cc
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 # Where the tool is installed.
 prefix="${prefix:-@prefix@}"
 PARALLEL=@PARALLEL@		# Am I in parallel mode?
@@ -39,7 +43,7 @@ H5TOOL_BIN="${prefix}/bin/${H5TOOL}"   # The path of the tool binary
 CMP='cmp -s'
 DIFF='diff -c'
 
-nerrors=0
+nerrors=$EXIT_SUCCESS
 verbose=${HDF5_VERBOSE:-1}      # 0: none; 1: default; 2: chatty; 3: everything
 test $verbose -gt 2 && set -x
 H5_NO_DEPRECATED_SYMBOLS=`grep '#define H5_NO_DEPRECATED_SYMBOLS ' ../src/H5pubconf.h`
@@ -343,7 +347,9 @@ if test -z "$HDF5_NOCLEANUP"; then
 fi
 
 if test $nerrors -eq 0 ; then
-   echo "All $H5TOOL tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
diff --git a/tools/h5dump/testh5dump.sh.in b/tools/h5dump/testh5dump.sh.in
--- a/tools/h5dump/testh5dump.sh.in
+++ b/tools/h5dump/testh5dump.sh.in
@@ -23,6 +23,10 @@ USE_FILTER_FLETCHER32="@USE_FILTER_FLETCHER32@"
 USE_FILTER_NBIT="@USE_FILTER_NBIT@"
 USE_FILTER_SCALEOFFSET="@USE_FILTER_SCALEOFFSET@"
 
+TESTNAME=h5dump
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 DUMPER=h5dump                     # The tool name
 DUMPER_BIN=`pwd`/$DUMPER          # The path of the tool binary
 TESTDIR=`pwd`/../testfiles
@@ -512,8 +516,9 @@ TOOLTEST textlinkfar.ddl textlinkfar.h5
 TOOLTEST tdset_idx.ddl -p -H tdset_idx.h5
 
 if test $nerrors -eq 0 ; then
-   echo "All $DUMPER tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
-
diff --git a/tools/h5dump/testh5dumpxml.sh.in b/tools/h5dump/testh5dumpxml.sh.in
--- a/tools/h5dump/testh5dumpxml.sh.in
+++ b/tools/h5dump/testh5dumpxml.sh.in
@@ -15,6 +15,10 @@
 #
 # Tests for the h5dump tool
 
+TESTNAME=h5dumpxml
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 H5_LONE_COLON="@H5_LONE_COLON@"
 
 DUMPER=h5dump               # The tool name
@@ -185,10 +189,10 @@ TOOLTEST torderattr3.h5.xml --xml -H --sort_by=creation_order --sort_order=ascen
 TOOLTEST torderattr4.h5.xml --xml -H --sort_by=creation_order --sort_order=descending torderattr.h5
 
 
-
-
 if test $nerrors -eq 0 ; then
-   echo "All $DUMPER tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
