[svn-r7618] Purpose:     Add check
Description:
    Added a check to make sure that the "tr" program actually works.

Platforms tested:
    Linux (small fix and only to configure)

Misc. update:

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1535,6 +1535,18 @@ set >&5
 echo "$as_me:$LINENO: result: done" >&5
 echo "${ECHO_T}done" >&6
 
+echo "$as_me:$LINENO: checking if tr works" >&5
+echo $ECHO_N "checking if tr works... $ECHO_C" >&6
+TRTEST=`echo "Test" | tr 'a-z,' 'A-Z '`
+if test $TRTEST != "TEST"; then
+  { { echo "$as_me:$LINENO: error: tr program doesn't work" >&5
+echo "$as_me: error: tr program doesn't work" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
+
 echo "$as_me:$LINENO: checking for cached host" >&5
 echo $ECHO_N "checking for cached host... $ECHO_C" >&6
 if test "${hdf5_cv_host+set}" = set; then
@@ -3979,7 +3991,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3982 "configure"' > conftest.$ac_ext
+  echo '#line 3994 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4520,7 +4532,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4523: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4535: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6327,7 +6339,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6330 "configure"
+#line 6342 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6425,7 +6437,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6428 "configure"
+#line 6440 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
