[svn-r7770] Purpose:     More Checks
Description:
    Added checks for correctly working "basename" and "xargs" programs.
    Mike McKay was having troubles with the xargs. The basename check was
    just a good idea.

Platforms tested:
    Verbena, Arabica, Modi4

Misc. update:

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1538,10 +1538,34 @@ echo "${ECHO_T}done" >&6
 
 echo "$as_me:$LINENO: checking if tr works" >&5
 echo $ECHO_N "checking if tr works... $ECHO_C" >&6
-TRTEST=`echo "Test" | tr 'a-z,' 'A-Z '`
-if test $TRTEST != "TEST"; then
+TR_TEST="`echo Test | tr 'a-z,' 'A-Z '`"
+if test $TR_TEST != "TEST"; then
   { { echo "$as_me:$LINENO: error: tr program doesn't work" >&5
 echo "$as_me: error: tr program doesn't work" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
+
+echo "$as_me:$LINENO: checking if basename works" >&5
+echo $ECHO_N "checking if basename works... $ECHO_C" >&6
+BASENAME_TEST="`basename /foo/bar/baz/qux/basename_works`"
+if test $BASENAME_TEST != "basename_works"; then
+  { { echo "$as_me:$LINENO: error: basename program doesn't work" >&5
+echo "$as_me: error: basename program doesn't work" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
+
+echo "$as_me:$LINENO: checking if xargs works" >&5
+echo $ECHO_N "checking if xargs works... $ECHO_C" >&6
+XARGS_TEST="`echo /foo/bar/baz/qux/xargs_works | xargs basename`"
+if test $XARGS_TEST != "xargs_works"; then
+  { { echo "$as_me:$LINENO: error: xargs program doesn't work" >&5
+echo "$as_me: error: xargs program doesn't work" >&2;}
    { (exit 1); exit 1; }; }
 else
   echo "$as_me:$LINENO: result: yes" >&5
@@ -3992,7 +4016,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3995 "configure"' > conftest.$ac_ext
+  echo '#line 4019 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4533,7 +4557,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4536: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4560: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6340,7 +6364,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6343 "configure"
+#line 6367 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6438,7 +6462,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6441 "configure"
+#line 6465 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
