[svn-r7093] Purpose:     MPE Fix
Description:
    The MPE stuff needed the lmpe library.

Solution:
    Added it.

Platforms tested:
    Copper (Small fix)

Misc. update:

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -30930,6 +30930,73 @@ else
   unset MPE
 fi
 
+
+echo "$as_me:$LINENO: checking for CLOG_Init in -llmpe" >&5
+echo $ECHO_N "checking for CLOG_Init in -llmpe... $ECHO_C" >&6
+if test "${ac_cv_lib_lmpe_CLOG_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llmpe  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char CLOG_Init ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+CLOG_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lmpe_CLOG_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_lmpe_CLOG_Init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_lmpe_CLOG_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_lmpe_CLOG_Init" >&6
+if test $ac_cv_lib_lmpe_CLOG_Init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLMPE 1
+_ACEOF
+
+  LIBS="-llmpe $LIBS"
+
+else
+  unset MPE
+fi
+
       ;;
     *)
       case "$withval" in
@@ -31260,6 +31327,73 @@ else
   LDFLAGS="$saved_LDFLAGS"; unset MPE
 fi
 
+
+echo "$as_me:$LINENO: checking for CLOG_Init in -llmpe" >&5
+echo $ECHO_N "checking for CLOG_Init in -llmpe... $ECHO_C" >&6
+if test "${ac_cv_lib_lmpe_CLOG_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llmpe  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char CLOG_Init ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+CLOG_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lmpe_CLOG_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_lmpe_CLOG_Init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_lmpe_CLOG_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_lmpe_CLOG_Init" >&6
+if test $ac_cv_lib_lmpe_CLOG_Init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLMPE 1
+_ACEOF
+
+  LIBS="-llmpe $LIBS"
+
+else
+  LDFLAGS="$saved_LDFLAGS"; unset MPE
+fi
+
       else
 
 echo "$as_me:$LINENO: checking for MPE_Init_log in -lmpe" >&5
@@ -31323,6 +31457,73 @@ if test $ac_cv_lib_mpe_MPE_Init_log = yes; then
 _ACEOF
 
   LIBS="-lmpe $LIBS"
+
+else
+  unset MPE
+fi
+
+
+echo "$as_me:$LINENO: checking for CLOG_Init in -llmpe" >&5
+echo $ECHO_N "checking for CLOG_Init in -llmpe... $ECHO_C" >&6
+if test "${ac_cv_lib_lmpe_CLOG_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llmpe  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char CLOG_Init ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+CLOG_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lmpe_CLOG_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_lmpe_CLOG_Init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_lmpe_CLOG_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_lmpe_CLOG_Init" >&6
+if test $ac_cv_lib_lmpe_CLOG_Init = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLMPE 1
+_ACEOF
+
+  LIBS="-llmpe $LIBS"
 
 else
   unset MPE
