[svn-r19939] Purpose: Moved the two shape same tests from testphdf5 to a separated executables, named t_shapesame. The shape same tests runs too long for testphdf5. In a separated executalbe, it will be easier to separate any errors in testphdf5 sub-tests from the shape same tests.
t_shapesame.c:
   Contains the shape same tests (cloned from t_rank_projection.c) plus
   a duplicate of "testphdf5.c" for now. After verifying it is correct, more
   cleanup is needed.
testphdf5.c:
   Removed the two shape same tests (chsssdrpio & cbhsssdrpio).
Makefile.am:
Makefile.in:
   Added t_shapesame as a new test executable.
   Removed t_rank_projections.c from part of testphdf5.
testph5.sh.in:
   Temporary added the "t_shapesame -p" test for testing shape same tests
   with MPIO-Posix VFD.

Tested: h5committested, plus serial jam.

diff --git a/testpar/testph5.sh.in b/testpar/testph5.sh.in
--- a/testpar/testph5.sh.in
+++ b/testpar/testph5.sh.in
@@ -60,6 +60,18 @@ TOOLTEST() {
 # testphdf5 test using the MPI-POSIX VFL driver
 TOOLTEST -p
 
+# Temporary patch:
+# Run t_shapesame this way. Need more permanent solution.
+TEST_APP_BIN=t_shapesame
+echo $RUNPARALLEL t_shapesame -p
+eval $RUNPARALLEL t_shapesame -p
+
+# Check if the command failed and increment nerrors if so.
+if test $? -ne 0 ; then
+    nerrors="`expr $nerrors + 1`"
+fi
+# Temporary patch ended.
+
 # Emit message about testing status
 if test $nerrors -eq 0 ; then
    echo "All $TEST_APP tests passed."
