[svn-r7276] Purpose: This is an omibus update to the h5dump program.
  1. Fixes bug 888
  2. updates XML output to 1.6

Description:

Solution:

Platforms tested:

verbena, arabica, copper (64)

Misc. update:
MANIFEST updated
Need to do release notes.

diff --git a/tools/h5dump/Makefile.in b/tools/h5dump/Makefile.in
--- a/tools/h5dump/Makefile.in
+++ b/tools/h5dump/Makefile.in
@@ -27,6 +27,7 @@ CPPFLAGS=-I. -I$(srcdir) -I$(top_builddir)/src -I$(top_srcdir)/src  \
 ##
 TEST_PROGS=h5dumpgentest
 TEST_SCRIPTS=$(srcdir)/testh5dump.sh
+TEST_SCRIPTS_XML=$(srcdir)/testh5dumpxml.sh
 
 ## These are our main targets: library and tools.
 ##
@@ -74,5 +75,83 @@ h5dump: h5dump.lo
 
 h5dumpgentest: h5dumpgentest.lo
 	@$(LT_LINK_EXE) $(CFLAGS) -o $@ h5dumpgentest.lo $(LIBTOOLS) $(LIBHDF5) $(LDFLAGS) $(LIBS)
+
+## Runs each test in order, passing $(TEST_FLAGS) to the program.
+## Since tests are done in a shell loop, "make -i" does apply inside it.
+## Set HDF5_Make_Ignore to a non-blank string to ignore errors inside the loop.
+## The timestamps give a rough idea how much time the tests use.
+##
+tests-xml: $(TEST_PROGS_XML) $(TEST_PROGS_PARA_XML) $(TEST_SCRIPTS_XML) $(LIB)
+check-xml test-xml _test-xml: tests-xml
+	@echo "===Tests begin `date`==="
+	@for test in $(TEST_PROGS_XML) dummy; do                                  \
+	   if test $$test != dummy; then				      \
+	      echo "============================";			      \
+	      echo "Testing $$test $(TEST_FLAGS)";			      \
+	      echo "============================";			      \
+	      srcdir="$(srcdir)"					      \
+		 $(RUNTEST) ./$$test $(TEST_FLAGS) ||			      \
+		 (test $$HDF5_Make_Ignore && echo "*** Error ignored") ||     \
+		 break;							      \
+	      echo "";							      \
+	   fi;								      \
+	done;								      \
+	test $$test = dummy || false
+	@if test -n "$(TEST_PROGS_PARA_XML)"; then				      \
+	    echo "**** Hint ****";					      \
+	    echo "Parallel test files reside in the current directory"	      \
+	         "by default.";						      \
+	    echo "Set HDF5_PARAPREFIX to use another directory. E.g.,";	      \
+	    echo "    HDF5_PARAPREFIX=/PFS/user/me";			      \
+	    echo "    export HDF5_PARAPREFIX";				      \
+	    echo "    make check";					      \
+	    echo "**** end of Hint ****";				      \
+	fi
+	@for test in $(TEST_PROGS_PARA_XML) dummy; do                             \
+	   if test $$test != dummy; then				      \
+	      echo "============================";			      \
+	      echo "Testing $$test $(TEST_FLAGS)";			      \
+	      echo "============================";			      \
+	      srcdir="$(srcdir)"					      \
+		 $(RUNPARALLEL) ./$$test $(TEST_FLAGS) ||		      \
+		 (test $$HDF5_Make_Ignore && echo "*** Error ignored") ||     \
+		 break;							      \
+	      echo "";							      \
+	   fi;								      \
+	done;								      \
+	test $$test = dummy || false
+	@for test in $(TEST_SCRIPTS_XML) dummy; do                                \
+	   if test $$test != dummy; then				      \
+	      echo "============================";			      \
+	      echo "Testing $$test $(TEST_FLAGS)";			      \
+	      echo "============================";			      \
+	      RUNSERIAL="$(RUNSERIAL)" RUNPARALLEL="$(RUNPARALLEL)"           \
+	         srcdir="$(srcdir)"					      \
+		 /bin/sh $$test $(TEST_FLAGS) ||		              \
+		 (test $$HDF5_Make_Ignore && echo "*** Error ignored") ||     \
+		 break;							      \
+	      echo "";							      \
+	   fi;								      \
+	done;								      \
+	test $$test = dummy || false
+	@echo "===Tests ended `date`==="
+	@for d in X $(SUBDIRS); do                                      \
+	    if test $$d != X; then                                      \
+	        (set -x; cd $$d && $(MAKE) tests) || exit 1;            \
+	    fi;                                                         \
+	done
+
+## Run test with different Virtual File Driver
+check-vfd-xml:
+	@for vfd in $(VFD_LIST) dummy; do				      \
+	    if test $$vfd != dummy; then                                      \
+		echo "============================";                          \
+		echo "Testing Virtual File Driver $$vfd";		      \
+		echo "============================";                          \
+		HDF5_DRIVER=$$vfd $(MAKE) check;			      \
+	    fi;								      \
+	done
+
+check-all: check check-xml
 
 @CONCLUDE@
