[svn-r27848] Description:     Clean up warnings and some normalization against trunk.
Tested:
    McaOSX/64 10.10.5 (amazon) w/serial & parallel
    (h5committest not required on this branch)

diff --git a/tools/h5diff/testh5diff.sh.in b/tools/h5diff/testh5diff.sh.in
--- a/tools/h5diff/testh5diff.sh.in
+++ b/tools/h5diff/testh5diff.sh.in
@@ -385,23 +385,23 @@ CLEAN_TESTFILES_AND_TESTDIR()
 while [ $# -gt 0 ]; do
     case "$1" in
     -p)	# reset the tool name and bin to run ph5diff tests
-  TESTNAME=ph5diff
-  H5DIFF=ph5diff               # The tool name
-  H5DIFF_BIN=`pwd`/$H5DIFF
-  pmode=yes
-  shift
-  ;;
+	TESTNAME=ph5diff
+	H5DIFF=ph5diff               # The tool name
+	H5DIFF_BIN=`pwd`/$H5DIFF
+	pmode=yes
+	shift
+	;;
     -h) # print help page
-  echo "$0 [-p] [-h]"
-  echo "    -p   run ph5diff tests"
-  echo "    -h   print help page"
-  shift
-  exit 0
-  ;;
+	echo "$0 [-p] [-h]"
+	echo "    -p   run ph5diff tests"
+	echo "    -h   print help page"
+	shift
+	exit 0
+	;;
     *)  # unknown option
         echo "$0: Unknown option ($1)"
-  exit 1
-  ;;
+	exit 1
+	;;
     esac
 done
 
@@ -452,11 +452,11 @@ TOOLTEST() {
     # Run test.
     TESTING $H5DIFF $@
     (
-  #echo "#############################"
-  #echo "Expected output for '$H5DIFF $@'"
-  #echo "#############################"
-  cd $TESTDIR
-  eval $RUNCMD $H5DIFF_BIN "$@"
+	#echo "#############################"
+	#echo "Expected output for '$H5DIFF $@'" 
+	#echo "#############################"
+	cd $TESTDIR
+	eval $RUNCMD $H5DIFF_BIN "$@"
     ) >$actual 2>$actual_err
     EXIT_CODE=$?
     # save actual and actual_err in case they are needed later.
@@ -485,7 +485,7 @@ TOOLTEST() {
         nerrors="`expr $nerrors + 1`"
         test yes = "$verbose" && $DIFF $expect $actual |sed 's/^/    /'
     else
-      # parallel mode output are often of different ordering from serial
+        # parallel mode output are often of different ordering from serial
         # output.  If the sorted expected and actual files compare the same,
         # it is safe to assume the actual output match the expected file.
         expect_sorted=expect_sorted
@@ -496,22 +496,22 @@ TOOLTEST() {
         # is done by serial mode.
         grep -v "EXIT CODE:" $expect_sorted > $expect_sorted.noexit
         mv $expect_sorted.noexit $expect_sorted
-  if $CMP $expect_sorted $actual_sorted; then
-      echo " PASSED"
-  else
-      echo "*FAILED*"
-      nerrors="`expr $nerrors + 1`"
-      if test yes = "$verbose"; then
-    echo "====Expected result ($expect_sorted) differs from actual result ($actual_sorted)"
-    $DIFF $expect_sorted $actual_sorted |sed 's/^/    /'
-    echo "====The actual output ($actual_sav)"
-    sed 's/^/    /' < $actual_sav
-    echo "====The actual stderr ($actual_err_sav)"
-    sed 's/^/    /' < $actual_err_sav
-    echo "====End of actual stderr ($actual_err_sav)"
-    echo ""
-      fi
-  fi
+	if $CMP $expect_sorted $actual_sorted; then
+	    echo " PASSED"
+	else
+	    echo "*FAILED*"
+	    nerrors="`expr $nerrors + 1`"
+	    if test yes = "$verbose"; then
+		echo "====Expected result ($expect_sorted) differs from actual result ($actual_sorted)"
+		$DIFF $expect_sorted $actual_sorted |sed 's/^/    /'
+		echo "====The actual output ($actual_sav)"
+		sed 's/^/    /' < $actual_sav 
+		echo "====The actual stderr ($actual_err_sav)"
+		sed 's/^/    /' < $actual_err_sav 
+		echo "====End of actual stderr ($actual_err_sav)"
+		echo ""
+	    fi
+	fi
     fi
 
     # Clean up output file
