[svn-r23307] HDFFV-8311: Correct test dependency             Remove h5ls references
Tested: local linux

diff --git a/tools/h5copy/testh5copy.sh.in b/tools/h5copy/testh5copy.sh.in
--- a/tools/h5copy/testh5copy.sh.in
+++ b/tools/h5copy/testh5copy.sh.in
@@ -57,9 +57,6 @@ $SRC_H5COPY_TESTFILES/h5copy_extlinks_trg.h5
 
 # List of expect files that will be copied over to local test dir
 LIST_OTHER_TEST_FILES="
-$SRC_H5COPY_TESTFILES/h5copy_extlinks_src.out.ls
-$SRC_H5COPY_TESTFILES/h5copy_ref.out.ls
-$SRC_H5COPY_TESTFILES/h5copytst.out.ls
 $SRC_H5COPY_TESTFILES/h5copy_misc1.out
 "
 
@@ -151,15 +148,6 @@ VERIFY()
 # Print a line-line message left justified in a field of 70 characters
 # beginning with the word "Verifying".
 #
-VERIFY_H5LS() 
-{
-    SPACES="                                                               "
-    echo "Verifying h5ls file structure $* $SPACES" | cut -c1-70 | tr -d '\012'
-}
-
-# Print a line-line message left justified in a field of 70 characters
-# beginning with the word "Verifying".
-#
 VERIFY_OUTPUT() 
 {
     SPACES="                                                               "
@@ -183,24 +171,34 @@ TOOLTEST()
 {
     actualout="$TESTDIR/tooltest.actualout"
     actualerr="$TESTDIR/tooltest.actualerr"
-     runh5diff=yes
-     if [ "$1" = -i ]; then
-      inputfile=$2
-     else
-      runh5diff=no
-     fi
-     if [ "$3" = -o ]; then
-      outputfile=$4
-     else 
-      runh5diff=no
-     fi
+    runh5diff=yes
+    if [ "$1" = -i ]; then
+        inputfile=$2
+    else
+        if [ "$1" = -f ]; then
+            inputfile=$4
+        else
+            inputfile=$3
+        fi
+        runh5diff=no
+    fi
+    if [ "$3" = -o ]; then
+        outputfile=$4
+    else 
+        if [ "$1" = -f ]; then
+            outputfile=$6
+        else
+            outputfile=$5
+        fi
+        runh5diff=no
+    fi
   
     TESTING $H5COPY $@
     (
-    echo "#############################"
-    echo " output for '$H5COPY $@'"
-    echo "#############################"
-    $RUNSERIAL $H5COPY_BIN $@
+        echo "#############################"
+        echo " output for '$H5COPY $@'"
+        echo "#############################"
+        $RUNSERIAL $H5COPY_BIN $@
     ) > $actualout 2> $actualerr
     RET=$?
     if [ $RET != 0 ]; then
@@ -210,15 +208,141 @@ TOOLTEST()
         nerrors="`expr $nerrors + 1`"
     else
         echo " PASSED"
+    
+        if [ $runh5diff != no ]; then
+            H5DIFFTEST $inputfile $outputfile $7 $9
+        fi
 
         # Clean up output file
         if test -z "$HDF5_NOCLEANUP"; then
-           rm -f $actualout $actualerr
+            rm -f $actualout $actualerr $outputfile
         fi
     fi
+}
+
+# TOOLTEST back-to-back
+TOOLTEST_PREFILL() 
+{
+    actualout="$TESTDIR/tooltest.actualout"
+    actualerr="$TESTDIR/tooltest.actualerr"
+    runh5diff=yes
+    if [ "$1" = -i ]; then
+        inputfile=$2
+    else
+        runh5diff=no
+    fi
+    if [ "$3" = -o ]; then
+        outputfile=$4
+    else 
+        runh5diff=no
+    fi
     
-    if [ $runh5diff != no ]; then
-     H5DIFFTEST $inputfile $outputfile $7 $9
+    grp_name=$5
+    grp_name2=$6
+    obj_name=$7
+    obj_name2=$8
+  
+    TESTING $H5COPY $@
+    (
+        echo "#############################"
+        echo " output for '$H5COPY $@'"
+        echo "#############################"
+        $RUNSERIAL $H5COPY_BIN  -i $inputfile -o $outputfile -v -s $grp_name -d $grp_name2 
+    ) > $actualout 2> $actualerr
+    RET=$?
+    if [ $RET != 0 ]; then
+        echo "*FAILED*"
+        echo "failed result is:"
+        cat $actualout
+        nerrors="`expr $nerrors + 1`"
+    else
+        TESTING $H5COPY $@
+        (
+            echo "#############################"
+            echo " output for '$H5COPY $@'"
+            echo "#############################"
+            $RUNSERIAL $H5COPY_BIN  -i $inputfile -o $outputfile -v -s $obj_name -d $obj_name2 
+        ) > $actualout 2> $actualerr
+        RET=$?
+        if [ $RET != 0 ]; then
+            echo "*FAILED*"
+            echo "failed result is:"
+            cat $actualout
+            nerrors="`expr $nerrors + 1`"
+        else
+            echo " PASSED"
+    
+            if [ $runh5diff != no ]; then
+                H5DIFFTEST $inputfile $outputfile $obj_name $obj_name2
+            fi
+        
+            # Clean up output file
+            if test -z "$HDF5_NOCLEANUP"; then
+                rm -f $actualout $actualerr $outputfile
+            fi
+        fi
+    fi
+}
+
+# TOOLTEST back-to-back
+TOOLTEST_SAME() 
+{
+    actualout="$TESTDIR/tooltest.actualout"
+    actualerr="$TESTDIR/tooltest.actualerr"
+    runh5diff=yes
+    if [ "$1" = -i ]; then
+        inputfile=$2
+    else
+        runh5diff=no
+    fi
+    if [ "$3" = -o ]; then
+        outputfile=$4
+    else 
+        runh5diff=no
+    fi
+    
+    grp_name=$5
+    grp_name2=$6
+  
+    TESTING $H5COPY $@
+    (
+        echo "#############################"
+        echo " output for '$H5COPY $@'"
+        echo "#############################"
+        $RUNSERIAL $H5COPY_BIN  -i $inputfile -o $outputfile -v -s $grp_name -d $grp_name 
+    ) > $actualout 2> $actualerr
+    RET=$?
+    if [ $RET != 0 ]; then
+        echo "*FAILED*"
+        echo "failed result is:"
+        cat $actualout
+        nerrors="`expr $nerrors + 1`"
+    else
+        TESTING $H5COPY $@
+        (
+            echo "#############################"
+            echo " output for '$H5COPY $@'"
+            echo "#############################"
+            $RUNSERIAL $H5COPY_BIN  -i $outputfile -o $outputfile -v -s $grp_name -d $grp_name2 
+        ) > $actualout 2> $actualerr
+        RET=$?
+        if [ $RET != 0 ]; then
+            echo "*FAILED*"
+            echo "failed result is:"
+            cat $actualout
+            nerrors="`expr $nerrors + 1`"
+        else
+            echo " PASSED"
+    
+            if [ $runh5diff != no ]; then
+                H5DIFFTEST $outputfile $outputfile $grp_name $grp_name2
+            fi
+        
+            # Clean up output file
+            if test -z "$HDF5_NOCLEANUP"; then
+                rm -f $actualout $actualerr $outputfile
+            fi
+        fi
     fi
 }
 
@@ -259,18 +383,18 @@ TOOLTEST_FAIL()
     actualerr_sav=${actualerr}-sav
     shift
     if [ "$1" = -i ]; then
-      inputfile=$2
+        inputfile=$2
     fi
     if [ "$3" = -o ]; then
-      outputfile=$4
+        outputfile=$4
     fi
 
     TESTING $H5COPY $@
     (
-    #echo "#############################"
-    #echo " output for '$H5COPY $@'"
-    #echo "#############################"
-    $RUNSERIAL $H5COPY_BIN $@
+        #echo "#############################"
+        #echo " output for '$H5COPY $@'"
+        #echo "#############################"
+        $RUNSERIAL $H5COPY_BIN $@
     ) > $actualout 2> $actualerr
 
     RET=$?
@@ -298,7 +422,7 @@ TOOLTEST_FAIL()
 
     # Clean up output file
     if test -z "$HDF5_NOCLEANUP"; then
-       rm -f $actualout $actualerr $actualout_sav $actualerr_sav
+        rm -f $actualout $actualerr $actualout_sav $actualerr_sav $outputfile
     fi
 }
 
@@ -311,10 +435,10 @@ H5DIFFTEST()
     $RUNSERIAL $H5DIFF_BIN -q "$@" 
     RET=$?
     if [ $RET != 0 ] ; then
-         echo "*FAILED*"
-         nerrors="`expr $nerrors + 1`"
+        echo "*FAILED*"
+        nerrors="`expr $nerrors + 1`"
     else
-         echo " PASSED"
+        echo " PASSED"
     fi
 }
 
@@ -327,48 +451,11 @@ H5DIFFTEST_FAIL()
     RET=$?
 
     if [ $h5haveexitcode = 'yes' -a $RET != 1 ] ; then
-         echo "*FAILED*"
-         nerrors="`expr $nerrors + 1`"
+        echo "*FAILED*"
+        nerrors="`expr $nerrors + 1`"
     else
-         echo " PASSED"
+        echo " PASSED"
     fi
-}
-
-# Call the h5ls tool to verify the correct output data in the destination file
-#
-H5LSTEST() 
-{
-    expect="$TESTDIR/`basename $1 .h5`.ls"
-    actual="$TESTDIR/`basename $1 .h5`.ls.actualout"
-
-    # Stderr is included in stdout so that the diff can detect
-    # any unexpected output from that stream too.
-    #
-    # Note:  The modification time and storage utilization are masked off
-    #   so that the output is more portable
-    VERIFY_H5LS  $@
-    (
-      $RUNSERIAL $H5LS_BIN $H5LS_ARGS $@
-    ) 2>&1 |sed 's/Modified:.*/Modified:  XXXX-XX-XX XX:XX:XX XXX/' |sed 's/Storage:.*/Storage:   <details removed for portability>/' >$actual
-
-
-   if [ ! -f $expect ]; then
-    # Create the expect file if it doesn't yet exist.
-    echo " CREATED"
-    cp $actual $expect
-   elif $CMP $expect $actual; then
-      echo " PASSED"
-   else
-      echo "*FAILED*"
-      echo "    Expected result (*.ls) differs from actual result (*.out)"
-      nerrors="`expr $nerrors + 1`"
-      test yes = "$verbose" && $DIFF $expect $actual |sed 's/^/    /'
-   fi
-
-   # Clean up output file
-   if test -z "$HDF5_NOCLEANUP"; then
-      rm -f $actual $actual_err
-   fi
 }
 
 # Copy single datasets of various forms from one group to another,
@@ -379,82 +466,54 @@ H5LSTEST()
 COPY_OBJECTS() 
 {
     TESTFILE="$TESTDIR/h5copytst.h5"
-    FILEOUT="$TESTDIR/`basename h5copytst.h5 .h5`.out.h5"
 
-    # Remove any output file left over from previous test run
-    rm -f $FILEOUT
-
-    echo "Testing from `basename $TESTFILE` to `basename $FILEOUT` for the following tests:"
     echo "Test copying various forms of datasets"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s simple     -d simple
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s chunk      -d chunk
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s compact    -d compact
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s compound   -d compound
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s compressed -d compressed
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s named_vl   -d named_vl
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s nested_vl  -d nested_vl
+    TOOLTEST -i $TESTFILE -o $TESTDIR/simple.out.h5 -v -s simple     -d simple
+    TOOLTEST -i $TESTFILE -o $TESTDIR/chunk.out.h5 -v -s chunk      -d chunk
+    TOOLTEST -i $TESTFILE -o $TESTDIR/compact.out.h5 -v -s compact    -d compact
+    TOOLTEST -i $TESTFILE -o $TESTDIR/compound.out.h5 -v -s compound   -d compound
+    TOOLTEST -i $TESTFILE -o $TESTDIR/compressed.out.h5 -v -s compressed -d compressed
+    TOOLTEST -i $TESTFILE -o $TESTDIR/named_vl.out.h5 -v -s named_vl   -d named_vl
+    TOOLTEST -i $TESTFILE -o $TESTDIR/nested_vl.out.h5 -v -s nested_vl  -d nested_vl
 
     echo "Test copying dataset within group in source file to root of destination"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s grp_dsets/simple  -d simple_top
+    TOOLTEST -i $TESTFILE -o $TESTDIR/simple_top.out.h5 -v -s grp_dsets/simple  -d simple_top
 
     echo "Test copying & renaming dataset"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s compound   -d rename
+    TOOLTEST -i $TESTFILE -o $TESTDIR/dsrename.out.h5 -v -s compound   -d rename
 
     echo "Test copying empty, 'full' & 'nested' groups"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s grp_empty  -d grp_empty
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s grp_dsets  -d grp_dsets
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s grp_nested -d grp_nested
+    TOOLTEST -i $TESTFILE -o $TESTDIR/grp_empty.out.h5 -v -s grp_empty  -d grp_empty
+    TOOLTEST -i $TESTFILE -o $TESTDIR/grp_dsets.out.h5 -v -s grp_dsets  -d grp_dsets
+    TOOLTEST -i $TESTFILE -o $TESTDIR/grp_nested.out.h5 -v -s grp_nested -d grp_nested
 
     echo "Test copying dataset within group in source file to group in destination"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s /grp_dsets/simple  -d /grp_dsets/simple_group
+    TOOLTEST_PREFILL -i $TESTFILE -o $TESTDIR/simple_group.out.h5 grp_dsets grp_dsets /grp_dsets/simple /grp_dsets/simple_group
 
     echo "Test copying & renaming group"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s grp_dsets  -d grp_rename
+    TOOLTEST -i $TESTFILE -o $TESTDIR/grp_rename.out.h5 -v -s grp_dsets  -d grp_rename
 
     echo "Test copying 'full' group hierarchy into group in destination file"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s grp_dsets  -d /grp_rename/grp_dsets
+    TOOLTEST_PREFILL -i $TESTFILE -o $TESTDIR/grp_dsets_rename.out.h5 grp_dsets grp_rename grp_dsets /grp_rename/grp_dsets
 
     echo "Test copying objects into group hier. that doesn't exist yet in destination file"
-    TOOLTEST -i $TESTFILE -o $FILEOUT -vp -s simple    -d /A/B1/simple
-    TOOLTEST -i $TESTFILE -o $FILEOUT -vp -s simple    -d /A/B2/simple2
-    TOOLTEST -i $TESTFILE -o $FILEOUT -vp -s /grp_dsets/simple    -d /C/D/simple
-    TOOLTEST -i $TESTFILE -o $FILEOUT -vp -s /grp_dsets -d /E/F/grp_dsets
-    TOOLTEST -i $TESTFILE -o $FILEOUT -vp -s /grp_nested -d /G/H/grp_nested
-
-    # Verify that the file created above is correct
-    H5LSTEST $FILEOUT
-
-    # Remove output file created, if the "no cleanup" environment variable is
-    #   not defined
-    if test -z "$HDF5_NOCLEANUP"; then
-        rm -f $FILEOUT
-    fi
+    TOOLTEST -i $TESTFILE -o $TESTDIR/A_B1_simple.out.h5 -vp -s simple    -d /A/B1/simple
+    TOOLTEST -i $TESTFILE -o $TESTDIR/A_B2_simple2.out.h5 -vp -s simple    -d /A/B2/simple2
+    TOOLTEST -i $TESTFILE -o $TESTDIR/C_D_simple.out.h5 -vp -s /grp_dsets/simple    -d /C/D/simple
+    TOOLTEST -i $TESTFILE -o $TESTDIR/E_F_grp_dsets.out.h5 -vp -s /grp_dsets -d /E/F/grp_dsets
+    TOOLTEST -i $TESTFILE -o $TESTDIR/G_H_grp_nested.out.h5 -vp -s /grp_nested -d /G/H/grp_nested
 }
 
 # Copy references in various way.
-# adding to the destination file each time compare the result
 #
 # Assumed arguments:
 # <none>
 COPY_REFERENCES() 
 {
     TESTFILE="$TESTDIR/h5copy_ref.h5"
-    FILEOUT="$TESTDIR/`basename h5copy_ref.h5 .h5`.out.h5"
-
-    # Remove any output file left over from previous test run
-    rm -f $FILEOUT
 
     echo "Test copying object and region references"
-    TOOLTEST -f ref -i $TESTFILE -o $FILEOUT -v -s / -d /COPY
-
-    # Verify that the file created above is correct
-    H5LSTEST $FILEOUT
-
-    # Remove output file created, if the "no cleanup" environment variable is
-    #   not defined
-    if test -z "$HDF5_NOCLEANUP"; then
-        rm -f $FILEOUT
-    fi
+    TOOLTEST_F -f ref -i $TESTFILE -o $TESTDIR/region_ref.out.h5 -v -s / -d /COPY
 }
 
 # Copy external links.
@@ -465,43 +524,30 @@ COPY_REFERENCES()
 COPY_EXT_LINKS() 
 {
     TESTFILE="$TESTDIR/h5copy_extlinks_src.h5"
-    FILEOUT="$TESTDIR/`basename h5copy_extlinks_src.h5 .h5`.out.h5"
-
-    # Remove any output file left over from previous test run
-    rm -f $FILEOUT
 
     echo "Test copying external link directly without -f ext"
-    TOOLTEST -v -i $TESTFILE -o $FILEOUT -s /group_ext/extlink_dset -d /copy1_dset
+    TOOLTEST -v -i $TESTFILE -o $TESTDIR/ext_link.out.h5 -s /group_ext/extlink_dset -d /copy1_dset
 
     echo "Test copying external link directly with -f ext"
-    TOOLTEST -f ext -i $TESTFILE -o $FILEOUT -v -s /group_ext/extlink_dset -d /copy2_dset
+    TOOLTEST_F -f ext -i $TESTFILE -o $TESTDIR/ext_link_f.out.h5 -v -s /group_ext/extlink_dset -d /copy2_dset
 
     echo "Test copying dangling external link (no obj) directly without -f ext"
-    TOOLTEST -v -i $TESTFILE -o $FILEOUT -s /group_ext/extlink_notyet1 -d /copy_dangle1_1
+    TOOLTEST -v -i $TESTFILE -o $TESTDIR/ext_dangle_noobj.out.h5 -s /group_ext/extlink_notyet1 -d /copy_dangle1_1
 
     echo "Test copying dangling external link (no obj) directly with -f ext"
-    TOOLTEST -f ext -i $TESTFILE -o $FILEOUT -v -s /group_ext/extlink_notyet1 -d /copy_dangle1_2
+    TOOLTEST_F -f ext -i $TESTFILE -o $TESTDIR/ext_dangle_noobj_f.out.h5 -v -s /group_ext/extlink_notyet1 -d /copy_dangle1_2
 
     echo "Test copying dangling external link (no file) directly without -f ext"
-    TOOLTEST -v -i $TESTFILE -o $FILEOUT -s /group_ext/extlink_notyet2 -d /copy_dangle2_1
+    TOOLTEST -v -i $TESTFILE -o $TESTDIR/ext_dangle_nofile.out.h5 -s /group_ext/extlink_notyet2 -d /copy_dangle2_1
 
     echo "Test copying dangling external link (no file) directly with -f ext"
-    TOOLTEST -f ext -i $TESTFILE -o $FILEOUT -v -s /group_ext/extlink_notyet2 -d /copy_dangle2_2
+    TOOLTEST_F -f ext -i $TESTFILE -o $TESTDIR/ext_dangle_nofile_f.out.h5 -v -s /group_ext/extlink_notyet2 -d /copy_dangle2_2
 
     echo "Test copying a group contains external links without -f ext"
-    TOOLTEST -v -i $TESTFILE -o $FILEOUT -s /group_ext -d /copy1_group
+    TOOLTEST -v -i $TESTFILE -o $TESTDIR/ext_link_group.out.h5 -s /group_ext -d /copy1_group
 
     echo "Test copying a group contains external links with -f ext"
-    TOOLTEST -f ext -v -i $TESTFILE -o $FILEOUT -s /group_ext -d /copy2_group
-
-    # Verify that the file created above is correct
-    H5LSTEST $FILEOUT
-
-    # Remove output file created, if the "no cleanup" environment variable is
-    #   not defined
-    if test -z "$HDF5_NOCLEANUP"; then
-        rm -f $FILEOUT
-    fi
+    TOOLTEST_F -f ext -i $TESTFILE -o $TESTDIR/ext_link_group_f.out.h5 -v -s /group_ext -d /copy2_group
 }
 
 # Test misc.
@@ -511,28 +557,13 @@ COPY_EXT_LINKS()
 TEST_MISC() 
 {
     TESTFILE="$TESTDIR/h5copytst.h5"
-    FILEOUT="$TESTDIR/`basename h5copytst.h5 .h5`.out.h5"
-
-    # Remove any output file left over from previous test run
-    rm -f $h5copy_misc1.out.h5
 
     echo "Test copying object into group which doesn't exist, without -p"
-    TOOLTEST_FAIL h5copy_misc1.out -v -i $TESTFILE -o $TESTDIR/h5copy_misc1.out.h5 -s /simple  -d /g1/g2/simple
+    TOOLTEST_FAIL h5copy_misc1.out -i $TESTFILE -o $TESTDIR/h5copy_misc1.out.h5 -v -s /simple  -d /g1/g2/simple
 
     echo "Test copying objects to the same file "
-    rm -f $FILEOUT
-    # create temporary test file ($FILEOUT) with some objects
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s /simple -d /simple 
-    TOOLTEST -i $TESTFILE -o $FILEOUT -v -s /grp_dsets  -d /grp_dsets
-    # actual test cases
-    TOOLTEST -i $FILEOUT -o $FILEOUT -v -s /simple -d /simple_cp
-    TOOLTEST -i $FILEOUT -o $FILEOUT -v -s /grp_dsets  -d /grp_dsets_cp
-
-    # Remove output file created, if the "no cleanup" environment variable is
-    #   not defined
-    if test -z "$HDF5_NOCLEANUP"; then
-        rm -f $FILEOUT
-    fi
+    TOOLTEST_SAME -i $TESTFILE -o $TESTDIR/samefile1.out.h5 /simple /simple_cp 
+    TOOLTEST_SAME -i $TESTFILE -o $TESTDIR/samefile2.out.h5 /grp_dsets /grp_dsets_cp
 }
 
 ##############################################################################
