Remove use of err files in autotools test scripts (#4461)

diff --git a/tools/test/misc/testh5clear.sh.in b/tools/test/misc/testh5clear.sh.in
--- a/tools/test/misc/testh5clear.sh.in
+++ b/tools/test/misc/testh5clear.sh.in
@@ -30,6 +30,7 @@ CP='cp'
 DIRNAME='dirname'
 LS='ls'
 AWK='awk'
+GREP='grep'
 
 SUCCEED=0
 FAIL=1
@@ -61,8 +62,6 @@ test -d $TESTDIR || mkdir -p $TESTDIR
 # copy test files and expected output files from source dirs to test dir
 #
 COPY_TESTFILES="
-$SRC_H5CLEAR_OUTFILES/h5clear_open_fail.err
-$SRC_H5CLEAR_OUTFILES/h5clear_no_mdc_image.err
 $SRC_H5CLEAR_OUTFILES/h5clear_usage.ddl
 $SRC_H5CLEAR_OUTFILES/h5clear_missing_file.ddl
 $SRC_H5CLEAR_OUTFILES/h5clear_status_noclose_after_size.ddl
@@ -178,7 +177,6 @@ TOOLTEST_OUT() {
     expected=$5
     # Prepare expected and actual output
     expect="$TESTDIR/$expected"
-    expect_err="$TESTDIR/`basename $expected .ddl`.err"
     actual="$TESTDIR/`basename $expected .ddl`.out"
     actual_err="$TESTDIR/`basename $expected .ddl`.out.err"
     actual_sav=${actual}-sav
@@ -201,18 +199,16 @@ TOOLTEST_OUT() {
         $RM $actual $actual_err $actual_sav $actual_err_sav
     fi
 }
-# same as TOOLTEST_OUT just compare stderr
+# same as TOOLTEST_OUT just grep stderr
 TOOLTEST_ERR() {
     fname=$1
-    option1=$2
-    option2=$3
-    option3=$4
-    expected=$5
+    expected=$2
+    option1=$3
+    option2=$4
+    option3=$5
     # Prepare expected and actual output
-    expect_err="$TESTDIR/$expected"
-    expect="$TESTDIR/`basename $expected .err`.ddl"
-    actual="$TESTDIR/`basename $expected .err`.out"
-    actual_err="$TESTDIR/`basename $expected .err`.out.err"
+    actual="$TESTDIR/`basename $fname .h5`.out"
+    actual_err="$TESTDIR/`basename $fname .h5`.out.err"
     actual_sav=${actual}-sav
     actual_err_sav=${actual_err}-sav
 
@@ -225,9 +221,15 @@ TOOLTEST_ERR() {
     cp $actual $actual_sav
     cp $actual_err $actual_err_sav
 
-    # Compare output
-    COMPARE_OUT $expect_err $actual_err
-
+    # grep output
+    $GREP "$expected" $actual_err > /dev/null
+    if test $? -eq 0; then
+        echo "PASSED"
+    else
+        echo "*FAILED*"
+        echo "    Expected text not found in actual result (*.out.err)"
+        nerrors="`expr $nerrors + 1`"
+    fi
     # Clean up output file
     if test -z "$HDF5_NOCLEANUP"; then
         $RM $actual $actual_err $actual_sav $actual_err_sav
@@ -305,11 +307,11 @@ TOOLTEST_OUT "" "" "" "" h5clear_usage.ddl
 TOOLTEST_OUT junk.h5 "" "" "" h5clear_usage.ddl
 TOOLTEST_OUT orig_h5clear_sec2_v3.h5 "" "" "" h5clear_usage.ddl
 TOOLTEST_OUT "" -m "" "" h5clear_missing_file.ddl
-TOOLTEST_ERR junk.h5 -s "" "" h5clear_open_fail.err
+TOOLTEST_ERR junk.h5 "h5clear error" -s "" ""
 TOOLTEST_OUT "" -m -s "" h5clear_missing_file.ddl
-TOOLTEST_ERR junk.h5 -m -s "" h5clear_open_fail.err
-TOOLTEST_ERR orig_h5clear_sec2_v2.h5 -m "" "" h5clear_no_mdc_image.err
-TOOLTEST_ERR orig_h5clear_sec2_v0.h5 -s -m "" h5clear_no_mdc_image.err
+TOOLTEST_ERR junk.h5 "h5clear error" -m -s ""
+TOOLTEST_ERR orig_h5clear_sec2_v2.h5 "h5clear warning" -m "" ""
+TOOLTEST_ERR orig_h5clear_sec2_v0.h5 "h5clear warning" -s -m ""
 #
 #
 # The following are tests to verify the expected exit code from h5clear:
@@ -339,8 +341,8 @@ TOOLTEST h5clear_sec2_v0.h5 -l -m $FAIL
 #
 #
 # h5clear_mdc_image.h5 already has cache image removed earlier, verify the expected warning from h5clear:
-TOOLTEST_ERR mod_h5clear_mdc_image.h5 -m "" "" h5clear_no_mdc_image.err
-TOOLTEST_ERR mod_h5clear_mdc_image.h5 -s -m "" h5clear_no_mdc_image.err
+TOOLTEST_ERR mod_h5clear_mdc_image.h5 "h5clear warning" -m "" ""
+TOOLTEST_ERR mod_h5clear_mdc_image.h5 "h5clear warning" -s -m ""
 #
 #
 #
@@ -378,7 +380,7 @@ OPEN_CHK h5clear_sec2_v2.h5 $SUCCEED
 # "h5clear -s --increment=0 h5clear_status_noclose.h5"  (clear status_flag, EOA = MAX(EOA, EOF) + 0)
 #                                                       (no output, check exit code)
 # "h5clear --filesize h5clear_status_noclose_user.h5"   (print EOA/EOF after the last action)
-TOOLTEST_ERR h5clear_status_noclose.h5 --filesize "" "" h5clear_open_fail.err
+TOOLTEST_ERR h5clear_status_noclose.h5 "h5clear error:" --filesize "" ""
 TOOLTEST h5clear_status_noclose.h5 -s --increment=0 $SUCCEED
 TOOLTEST_OUT h5clear_status_noclose.h5 --filesize "" "" h5clear_status_noclose_after_size.ddl
 #
