[svn-r16670] Interrim checkin of journal file modifications supporting recognition and rejection of attempts to apply the wrong journal file to a corrupt HDF5 file.  Specifically, I made the following changes:
1) Moved all journaling data into the journaling in progress superblock 
   extension message.

2) Added a "magic number" to the journaling in progress message, with 
   the same "magic number being added to the header of the associated 
   journal file.

3) Modifications to library test code to support the above.

4) Modified h5recover to examine the supplied hdf5 file, determine if 
   it is in fact a HDF5 file, if so determine if it is marked as having
   journaling in progress, and if it does, extract the contents of the
   journaling in progress super block extension message.

5) Modified h5recover to examine the supplied journal file, determine
   if it is in fact a HDF5 journal file, and if so, extract the data 
   from its header.

6) Modified h5recover to refuse to apply the supplied journal file to 
   the supplied HDF5 file unless the "magic numbers" obtained from these
   files matches.

7) Added an examine option to h5recover that causes it to examine and
   report on the supplied files, but do nothing.  This option exists 
   primarily to facilitate testing, but I expect that some users will
   find it useful as well.

8) Added test code to exercise items 4-7.  Note that while I have tried 
   to cover the more likely cases, this test code is extremely cursory.
   In particular, the code to examine the supplied HDF5 file is barely 
   tested at all.  Need a library of HDF5 files exibiting the full range
   of possible super block and super block extension message structures 
   to test this properly.  

9) In passing, tighened up the code that controls dumps of "possibly 
   significant" differences between the contents of the control and 
   recovered data sets in the h5recover.  It should now ignore one 
   integer matches in what appears to be garbage raw data.

Tested:  serial and parallel on Phoenix 
         serial and parallel on Jam
         serial on Linew
         serial on Liberty

         All tests were done in debug mode.

diff --git a/tools/h5recover/testh5recover.sh.in b/tools/h5recover/testh5recover.sh.in
--- a/tools/h5recover/testh5recover.sh.in
+++ b/tools/h5recover/testh5recover.sh.in
@@ -179,6 +179,127 @@ MYH5DIFF(){
 
 ##############################################################################
 ##                                                                          ##
+## The following function is used to perform a series of test on the        ##
+## output generated by h5recover, and its ability to reject mis-matched     ##
+## HDF5/journal file pairs, or HDF5 files that are not or cannot be         ##
+## journaled.                                                               ##
+##                                                                          ##
+## The basic idea is to do run h5recover on predefined hdf5 files and       ##
+## journals and compare the stdout and stderr output generated with         ##
+## architypes.  The matter is somewhat complicated by the flags needed for  ##
+## different tests -- but the concept is as above.                          ##
+##                                                                          ##
+##############################################################################
+
+
+run_h5recover_output_test() {
+
+    return_code=0
+    BASE_NAME=$1
+    FLAGS=$2
+    COMMENT=$3
+
+    TESTING $COMMENT
+
+    cp ./testfiles/${BASE_NAME}.h5 .
+    cp ./testfiles/${BASE_NAME}.jnl .
+
+    ( $RUNSERIAL ./h5recover -j ${BASE_NAME}.jnl -n ${FLAGS} ${BASE_NAME}.h5 \
+                 > ${BASE_NAME}.stdout ) 2> ${BASE_NAME}.stderr
+
+    # check stdout
+
+    ($DIFF ./testfiles/${BASE_NAME}.stdout ./${BASE_NAME}.stdout > \
+        ./${BASE_NAME}.stdout.stdout) 2> ./${BASE_NAME}.stdout.stderr
+
+    # check both return code and contents of stdout and stderr files --
+    # report files different if either the return code isn't 0, or
+    # either of the output files is non-empty.
+    if [ $? != 0 ]
+    then
+
+        echo "$DIFF returned non-zero return code(1)."
+        return_code=1
+
+    else
+
+        if [ `wc -c < ./${BASE_NAME}.stdout.stdout` != '0' ]
+        then
+
+           # echo "#DIFF returned non-empty stdout file(1)."
+           return_code=1
+
+        else
+
+            if [ `wc -c < ./${BASE_NAME}.stdout.stderr` != '0' ]
+            then
+
+                # echo "$DIFF returned non-empty stderr file(1)."
+                return_code=1
+
+            fi
+        fi
+    fi
+
+    # check stderr
+
+    ($DIFF ./testfiles/${BASE_NAME}.stderr ./${BASE_NAME}.stderr > \
+        ./${BASE_NAME}.stderr.stdout) 2> ./${BASE_NAME}.stderr.stderr
+
+    # check both return code and contents of stdout and stderr files --
+    # report files different if either the return code isn't 0, or
+    # either of the output files is non-empty.
+    if [ $? != 0 ]
+    then
+
+        # echo "$DIFF returned non-zero return code(2)."
+        return_code=1
+
+    else
+
+        if [ `wc -c < ./${BASE_NAME}.stderr.stdout` != '0' ]
+        then
+
+            # echo "#DIFF returned non-empty stdout file(2)."
+            return_code=1
+
+        else
+
+            if [ `wc -c < ./${BASE_NAME}.stderr.stderr` != '0' ]
+            then
+
+                # echo "$DIFF returned non-empty stderr file(2)."
+                return_code=1
+
+            fi
+        fi
+    fi
+
+
+    # tidy up
+    rm -f ${BASE_NAME}.h5
+    rm -f ${BASE_NAME}.jnl
+    rm -f ${BASE_NAME}.stdout
+    rm -f ${BASE_NAME}.stdout.stdout
+    rm -f ${BASE_NAME}.stdout.stderr
+    rm -f ${BASE_NAME}.stderr
+    rm -f ${BASE_NAME}.stderr.stdout
+    rm -f ${BASE_NAME}.stderr.stderr
+
+    if [ $return_code = 0 ]; then
+        echo " PASSED"
+    else
+        echo "*FAILED*"
+        nerrors="`expr $nerrors + 1`"
+    fi
+
+    return $return_code
+
+}
+
+
+##############################################################################
+##                                                                          ##
 ## The following functions are used to perform a sort of "temporal scan"    ##
 ## of the possible HDF5 file and journal file value created by trecover.    ##
 ##                                                                          ##
@@ -322,7 +443,7 @@ try_h5recover() {
 
     rm -f try_h5recover.stdout try_h5recover.stderr
 
-    ( $RUNSERIAL ./h5recover -j $TRY_RECOVER_JNL_FILE $TRY_RECOVER_H5_FILE > \
+    ( $RUNSERIAL ./h5recover -j $TRY_RECOVER_JNL_FILE -f $TRY_RECOVER_H5_FILE > \
 		try_h5recover.stdout ) 2> try_h5recover.stderr
 
     if [ `wc -c < try_h5recover.stderr` != '0' ]
@@ -452,7 +573,7 @@ test_point() {
 
 	    	# echo "trecover.h5.jnl exists -- try to recover"
 
-		# echo "./h5recover -j trecover.h5.jnl trecover.h5"
+		# echo "./h5recover -j trecover.h5.jnl -f trecover.h5"
 
 		try_h5recover trecover.h5.jnl trecover.h5
 
@@ -622,15 +743,63 @@ run_jnl_invarient_test() {
 # default test setting
 TOOLTEST default.txt
 
-# async crash
-# Since the async crash is highly dependent on machine speeds, system load,
-# the results may not always match.  One would need to compare the results
-# against the expected results by hand.
+
+# h5recover output and journal rejection tests
 #
-# JRM -- 12/10/08
-# this test is now subsumed in the invarient test.  Delete code for 
-# this test eventually.
-# TOOLTEST async_crash.txt -a 0.05
+# Ideally, this set of tests should verify that h5recover can examine all
+# valid HDF5 files, detect whether the file is marked as having journaling
+# in progress, and read the magic number if so.
+#
+# Similarly, these tests should also verify that h5recover can validate
+# the journal file, and that it can reject journal files that don't match
+# the supplied HDF5 file.
+#
+# In practice, this set of tests if quite incomplete.  In particular,
+# the tests do not cover anything close to the full range of HDF5 files.
+# This must be fixed eventualy, but for now I think I have the more common
+# cases.
+#                                              JRM -- 4/2/09
+
+run_h5recover_output_test test00 " " "00 successful recovery"
+run_h5recover_output_test test01 "-x" "01 examine with recovery possible"
+run_h5recover_output_test test02 "-x -v" "02 verbose examine with recovery possible"
+run_h5recover_output_test test03 "-f" "03 successful recovery with empty journal"
+run_h5recover_output_test test04 "-x" "04 empty journal examine with recovery possible"
+run_h5recover_output_test test05 "-x -v" "05 verbose empty journal examine with recovery possible"
+run_h5recover_output_test test06 " " "06 magic mismatch journal rejection"
+run_h5recover_output_test test07 "-x" "07 examine with magic mismatch"
+run_h5recover_output_test test08 "-x -v" "08 verbose examine with magic mismatch"
+run_h5recover_output_test test09 " " "09 un-journaled file"
+run_h5recover_output_test test10 "-x" "10 examine un-journaled file"
+run_h5recover_output_test test11 "-x -v" "11 verbose examine un-journaled file"
+run_h5recover_output_test test12 " " "12 invalid journal file -- bad first char"
+run_h5recover_output_test test13 "-x" "13 examine invalid journal file -- bad first char"
+run_h5recover_output_test test14 "-x -v" "14 verbose examine invalid journal file -- bad first char"
+run_h5recover_output_test test15 " " "15 invalid journal file -- bad ver tag"
+run_h5recover_output_test test16 "-x" "16 examine invalid journal file -- bad ver tag"
+run_h5recover_output_test test17 "-x -v" "17 verbose examine invalid journal file -- bad ver tag"
+run_h5recover_output_test test18 " " "18 invalid journal file -- bad target tag"
+run_h5recover_output_test test19 "-x" "19 examine invalid journal file -- bad target tag"
+run_h5recover_output_test test20 "-x -v" "20 verbose examine invalid journal file -- bad target tag"
+run_h5recover_output_test test21 " " "21 invalid journal file -- bad magic tag"
+run_h5recover_output_test test22 "-x" "22 examine invalid journal file -- bad magic tag"
+run_h5recover_output_test test23 "-x -v" "23 verbose examine invalid journal file -- bad magic tag"
+run_h5recover_output_test test24 " " "24 invalid journal file -- bad date tag"
+run_h5recover_output_test test25 "-x" "25 examine invalid journal file -- bad date tag"
+run_h5recover_output_test test26 "-x -v" "26 verbose examine invalid journal file -- bad date tag"
+run_h5recover_output_test test27 " " "27 invalid journal file -- bad human readable tag"
+run_h5recover_output_test test28 "-x" "28 examine invalid journal file -- bad human readable tag"
+run_h5recover_output_test test29 "-x -v" "29 verbose examine invalid journal file -- bad human readable tag"
+run_h5recover_output_test test30 " " "30 invalid journal file -- bad ver val"
+run_h5recover_output_test test31 "-x" "31 examine invalid journal file -- bad ver val"
+run_h5recover_output_test test32 "-x -v" "32 verbose examine invalid journal file -- bad ver val"
+run_h5recover_output_test test33 " " "33 invalid journal file -- bad human readable val"
+run_h5recover_output_test test34 "-x" "34 examine invalid journal file -- bad human readable val"
+run_h5recover_output_test test35 "-x -v" "35 verbose examine invalid journal file -- bad human readable val"
+run_h5recover_output_test test36 " " "36 bad HDF5 file"
+run_h5recover_output_test test37 "-x" "37 examine bad HDF5 file"
+run_h5recover_output_test test38 "-x -v" "38 verbose examine bad HDF5 file"
+
 
 # Invarient test
 # This is a very different test from the previous TOOLTEST calls -- 
@@ -639,9 +808,6 @@ TOOLTEST default.txt
 # maintained.  see comments for details.
 run_jnl_invarient_test
 
-if test $nerrors -eq 0 ; then
-   echo "All $TOOL tests passed."
-fi
 
 if test $nerrors -eq 0 ; then
     echo "All $TOOL tests passed."
