Add grep tests to h5stat script

diff --git a/tools/test/h5stat/testh5stat.sh.in b/tools/test/h5stat/testh5stat.sh.in
--- a/tools/test/h5stat/testh5stat.sh.in
+++ b/tools/test/h5stat/testh5stat.sh.in
@@ -33,6 +33,7 @@ CP='cp'
 DIRNAME='dirname'
 LS='ls'
 AWK='awk'
+GREP='grep'
 
 nerrors=0
 verbose=yes
@@ -210,6 +211,54 @@ TOOLTEST() {
 }
 
 
+# Call the h5stat tool and grep for a value
+# txttype ERRTXT greps test error output, otherwise greps test output
+GREPTEST()
+{
+    txttype=$1
+    expectdata=$2
+    expect="$TESTDIR/$3"
+    actual="$TESTDIR/`basename $1 .ddl`.out"
+    actual_err="$TESTDIR/`basename $1 .ddl`.out.err"
+    actual_sav=${actual}-sav
+    actual_err_sav=${actual_err}-sav
+    shift
+    shift
+    shift
+    if [ "$1" = -i ]; then
+        inputfile=$2
+    fi
+
+    if [ "$3" = -o ]; then
+        outputfile=$4
+    fi
+
+    # Run test.
+    TESTING $H5COPY $@
+    (
+        $RUNSERIAL $H5COPY_BIN $@
+    ) > $actualout 2> $actualerr
+    RET=$?
+
+    if [ "$txttype" = "ERRTXT" ]; then
+        $GREP "$expectdata" $actualerr > /dev/null
+    else
+        $GREP "$expectdata" $actualout > /dev/null
+    fi
+
+    if [ $? -eq 0 ]; then
+        echo " PASSED"
+    else
+        echo " FAILED"
+        nerrors="`expr $nerrors + 1`"
+    fi
+
+    # Clean up output file
+    if test -z "$HDF5_NOCLEANUP"; then
+        rm -f $actual $actual_err
+    fi
+}
+
 # Print a "SKIP" message
 SKIP() {
     TESTING $STAT $@
@@ -259,7 +308,7 @@ TOOLTEST h5stat_idx.ddl h5stat_idx.h5
 #     -g -l 8
 #     --links=8
 #     --links=20 -g
-TOOLTEST h5stat_err1_links.ddl -l 0 h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small groups" h5stat_err1_links.ddl -l 0 h5stat_threshold.h5
 TOOLTEST h5stat_links1.ddl -g -l 8 h5stat_threshold.h5
 TOOLTEST h5stat_links2.ddl --links=8 h5stat_threshold.h5
 TOOLTEST h5stat_links3.ddl --links=20 -g h5stat_threshold.h5
@@ -274,7 +323,7 @@ TOOLTEST h5stat_links5.ddl -g -l 40000 h5stat_newgrat.h5
 #     -d --dims=-1 (incorrect threshold value)
 #     -gd -m 5
 #     -d --di=15
-TOOLTEST h5stat_err1_dims.ddl -d --dims=-1 h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small datasets" h5stat_err1_dims.ddl -d --dims=-1 h5stat_threshold.h5
 TOOLTEST h5stat_dims1.ddl -gd -m 5 h5stat_threshold.h5
 TOOLTEST h5stat_dims2.ddl -d --dims=15 h5stat_threshold.h5
 #
@@ -284,8 +333,8 @@ TOOLTEST h5stat_dims2.ddl -d --dims=15 h5stat_threshold.h5
 #    -AS -a 10
 #    -a 1
 #    -A --numattrs=25
-TOOLTEST h5stat_err1_numattrs.ddl -a -2 h5stat_threshold.h5
-TOOLTEST h5stat_err2_numattrs.ddl --numattrs h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small # of attributes" h5stat_err1_numattrs.ddl -a -2 h5stat_threshold.h5
+GREPTEST ERRTXT "Invalid threshold for small # of attributes" h5stat_err2_numattrs.ddl --numattrs h5stat_threshold.h5
 TOOLTEST h5stat_numattrs1.ddl -AS -a 10 h5stat_threshold.h5
 TOOLTEST h5stat_numattrs2.ddl -a 1 h5stat_threshold.h5
 TOOLTEST h5stat_numattrs3.ddl -A --numattrs=25 h5stat_threshold.h5
