Add help usage option

diff --git a/config/cmake/libh5cc.in b/config/cmake/libh5cc.in
--- a/config/cmake/libh5cc.in
+++ b/config/cmake/libh5cc.in
@@ -36,6 +36,27 @@ showconfigure()
   status=$?
 }
 
+usage() {
+  # "How-to use" message.
+  echo "usage: $prg [OPTIONS] <pkg-config line>"
+  echo "  OPTIONS:"
+  echo "    -help           This help message."
+  echo "    -show           Show the commands without executing them"
+  echo "    -showconfig     Show the HDF5 library configuration summary"
+  echo " "
+  echo "  <pkg-config line> - the pkg-config compile line options for the compiler"
+  echo "                    that was used to compile HDF5." 
+  echo "                    Use pkg-config --help for more information"
+  echo "                    on which options are available. $prg passes pkg-config options"
+  echo "                    through as those options use double-underscores."
+  echo " "
+  echo "                    NOTE: pkg-config is required to be installed on your system and"
+  echo "                    using --static requires a static version of the C runtime library"
+  echo "                    to be have been installed on your system."
+  echo " "
+  exit $EXIT_FAILURE
+}
+
 export PKG_CONFIG_PATH=$dir/lib/pkgconfig
 
 for arg in $@ ; do
@@ -46,6 +67,10 @@ for arg in $@ ; do
       ;;
     -show)
       echo @_PKG_CONFIG_COMPILER@ $@ `pkg-config $pc_args --define-variable=prefix=$dir --cflags --libs @_PKG_CONFIG_LIBNAME@`
+      exit $status
+      ;;
+    -help)
+      usage
       exit $status
       ;;
     --*)
