node local fusion

diff --git a/utils/subfiling_vfd/h5fuse.sh.in b/utils/subfiling_vfd/h5fuse.sh.in
--- a/utils/subfiling_vfd/h5fuse.sh.in
+++ b/utils/subfiling_vfd/h5fuse.sh.in
@@ -27,10 +27,12 @@ function usage() {
          configuration file either as a command-line argument, or the script will
          search for the *.config file in the current directory."
    echo ""
-   echo "usage: h5fuse.sh [-h] [-f filename] [-v] [-q]"
+   echo "usage: h5fuse.sh [-h] [-f filename] [-v] [-q] [-b] [-o]"
    echo "-h            Print this help."
    echo "-v            Verbose output."
    echo "-q            Quiet all output."
+   echo "-b            Bypass missing subfiles."
+   echo "-o filename   HDF5 output file."
    echo "-f filename   Subfile configuration file."
    echo ""
 }
@@ -48,7 +50,9 @@ function usage() {
 file_config=""
 verbose="false"
 quiet="false"
-while getopts "hqvf:" option; do
+bypass="false"
+hdf5_file=""
+while getopts "bhqvf:o:" option; do
    case $option in
       h) # display Help
          usage
@@ -57,8 +61,12 @@ while getopts "hqvf:" option; do
          file_config=$OPTARG;;
       q) # quiet all output
          quiet="true";;
+      b) # bypass missing subfiles
+         bypass="true";;
       v) # verbose output
          verbose="true";;
+      o) # HDF5 fused file
+         hdf5_file=$OPTARG;;
      \?) # Invalid option
          usage
          exit 1;;
@@ -99,10 +107,12 @@ if test -z "$stripe_size"; then
     exit $FAILED
 fi
 
-hdf5_file="$(grep "hdf5_file=" "$file_config"  | cut -d "=" -f2)"
-if test -z "$hdf5_file"; then
-    echo -e "$RED failed to find hdf5 output file in $file_config $NC"
-    exit $FAILED
+if [ "$hdf5_file" = "" ]; then
+    hdf5_file="$(grep "hdf5_file=" "$file_config"  | cut -d "=" -f2)"
+    if test -z "$hdf5_file"; then
+        echo -e "$RED failed to find hdf5 output file in $file_config $NC"
+        exit $FAILED
+    fi
 fi
 
 subfile_dir="$(grep "subfile_dir=" "$file_config"  | cut -d "=" -f2)"
@@ -113,9 +123,6 @@ fi
 
 # For bash 4.4+
 mapfile -t subfiles < <( sed -e '1,/subfile_dir=/d' "$file_config" )
-
-#subfiles=( $( sed -e '1,/subfile_dir=/d' "$file_config" ) )
-
 #for i in "${subfiles[@]}"; do
 #      echo "$i"
 #done
@@ -132,16 +139,21 @@ skip=0
 status=$nfiles
 START="$(date +%s%N)"
 
-icnt=0
 skip=0
 seek=0
 seek_cnt=0
 for i in "${subfiles[@]}"; do
     subfile="${subfile_dir}/${i}"
-      # Verify the file exists
+    fsize=0
+    # Verify the file exists
     if [ ! -f "${subfile}" ]; then
-        echo -e "$RED ERROR: file \"${subfile}\" does not exist. $NC"
-        exit $FAILED
+        if [ "${bypass}" == "false" ];then
+            echo -e "$RED ERROR: file \"${subfile}\" does not exist. $NC"
+            exit $FAILED
+        fi
+    else
+        # Get the number of bytes of the file
+        fsize=$(wc -c "${subfile}" | awk '{print $1}')
     fi
 
     # bs=BYTES read and write up to BYTES bytes at a time; overrides ibs and obs
@@ -151,10 +163,8 @@ for i in "${subfiles[@]}"; do
     # skip=N skip N ibs-sized blocks at start of input
 
     status=1
-    # Get the number of bytes of the file
-    fsize=$(wc -c "${subfile}" | awk '{print $1}')
 
-    # If the subfile is empty, skip fusing the remaining empty subfiles
+    # If the subfile is empty, skip fusing it
 
     if [ "$fsize" -ne 0 ]; then
         records_left=$fsize
@@ -168,25 +178,18 @@ for i in "${subfiles[@]}"; do
                 if [ "$verbose" == "true" ]; then
                     echo -e "$CYN" $err "$NC"
                 fi
-                icnt=$((icnt+1))
                 records_left=$((records_left-stripe_size))
                 skip=$((skip+1))
                 seek=$((seek_cnt+skip*nsubfiles))
             else
-                subfiles=("${subfiles[@]:0:icnt}" "${subfiles[@]:$((icnt+1))}")
                 status=0
                 skip=0
             fi
         done; wait
         seek_cnt=$((seek_cnt+1))
         seek=$seek_cnt
-
-    else
-
-        subfiles=()
-
     fi
-done; wait
+done
 
 END=$(( $(date +%s%N) - START ))
 DURATION_SEC=$(awk -vp="$END" -vq=0.000000001 'BEGIN{printf "%.4f" ,p * q}')
