[svn-r24645] - Add Neil's VL datatype changes from the Netvol to H5VLiod_common.c - Refactor VL datatype handling for datasets to use Neil's functions.   * Still can't handle complicated VLs (nested, compunds, etc...).   * Need MPI mercury plugin fix and to update Neil's buffer construction at server for IOD storage. - Fix and Update IOD storage for VL dataypes in arrays by algorithmically calculating the BLOB ID. - Add test for Array VL datatypes to the FF test suite. - Other minor fixes.

diff --git a/examples/run_ff_tests.sh.in b/examples/run_ff_tests.sh.in
--- a/examples/run_ff_tests.sh.in
+++ b/examples/run_ff_tests.sh.in
@@ -63,5 +63,13 @@ echo "Finished object test-----------------------------------------------"
 [ $RETVAL -ne 0 ] && echo "FAILED-----------------------------------------------"
 sleep 2
 
+echo "Starting VL datatypes for datasets test-----------------------------------------------"
+mpiexec -np $1 ./h5ff_server &> ff_output/server_obj &
+sleep 2 &&
+mpiexec -np $2 ./h5ff_client_vl_data
+RETVAL=$?
+echo "Finished object test-----------------------------------------------"
+[ $RETVAL -ne 0 ] && echo "FAILED-----------------------------------------------"
+
 echo "FF tests DONE ---------------------------------------------------"
 exit
