[svn-r11179] Purpose: Feature: check-clean target
Description:
'make check-clean' cleans up output files from tests.

Solution:
Tests create foo.chkexe and foo.log files.  Scripts create foo.chksh and
foo.logsh files.  'make check-clean' will clean these files up so that
the tests can be re-run.
Also suppressed some not-very-useful output of Makefiles when it would
echo commands.

Platforms tested:
mir, sleipnir, modi4

Misc. update:

diff --git a/c++/Makefile.in b/c++/Makefile.in
--- a/c++/Makefile.in
+++ b/c++/Makefile.in
@@ -284,13 +284,16 @@ H5FC_PP = $(bindir)/h5pfc
 # Serial tests create .log and .logsh files.  It's important only to clean log
 # files generated by HDF5's tests, because the .log suffix is used for
 # other files (e.g., config.log)!
-MOSTLYCLEANFILES = $(TEST_PROG_CHKEXE:.chkexe_=.chkexe)                    \
+# On the other hand, it is very hard to specify the exact name of .chksh and
+# .logsh files because some scripts live in the source tree, not the build
+# tree.  Thus, we clean all .logsh and .chksh files.
+CHECK_CLEANFILES = $(TEST_PROG_CHKEXE:.chkexe_=.chkexe)                    \
         $(TEST_PROG_PARA_CHKEXE:.chkexe_=.chkexe)                        \
-        $(TEST_SCRIPT_CHKSH:.chksh_=.chksh)                              \
-        $(TEST_SCRIPT_PARA_CHKSH:.chksh_=.chksh)                         \
         $(TEST_PROG_CHKEXE:.chkexe_=.log)                                \
-        $(TEST_SCRIPT_CHKSH:.chksh_=.logsh)
+        $(TEST_PROG_PARA_CHKEXE:.chkexe_=.log)                           \
+        *.chksh *.logsh
 
+MOSTLYCLEANFILES = $(CHECK_CLEANFILES)
 @BUILD_CXX_CONDITIONAL_TRUE@SUBDIRS = src test
 DIST_SUBDIRS = src test examples
 
@@ -632,24 +635,24 @@ check-install: installcheck
 
 # Clean and mostlyclean need to recurse into examples directory
 clean-local:
-	if test -f examples/Makefile; then                                \
+	@if test -f examples/Makefile; then                                \
 	  (cd examples && $(MAKE) $(AM_MAKEFLAGS) clean) || exit 1;       \
 	fi;
 mostlyclean-local:
-	if test -f examples/Makefile; then                                \
+	@if test -f examples/Makefile; then                                \
 	  (cd examples && $(MAKE) $(AM_MAKEFLAGS) mostlyclean) || exit 1; \
 	fi;
 
 # Install examples
 install-examples uninstall-examples:
-	(cd examples && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
+	@(cd examples && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
 
 # Check that examples can be successfully built 
 check-install:
-	$(MAKE) $(AM_MAKEFLAGS) installcheck 
+	@$(MAKE) $(AM_MAKEFLAGS) installcheck 
 
 installcheck-local:
-	(cd examples && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
+	@(cd examples && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
 
 # lib/progs/tests targets recurse into subdirectories. build-* targets
 # build files in this directory.
@@ -659,7 +662,7 @@ build-lib: $(BUILT_SOURCES) $(LIB)
 build-progs: $(BUILT_SOURCES) $(LIB) $(PROGS)
 build-tests: $(BUILT_SOURCES) $(LIB) $(PROGS) $(TESTS)
 
-lib progs tests check-s check-p ::
+lib progs tests check-s check-p check-clean ::
 	@$(MAKE) $(AM_MAKEFLAGS) build-$@ || exit 1;
 	@for d in X $(SUBDIRS); do                                             \
 	    if test $$d != X && test $$d != .; then                           \
@@ -678,6 +681,10 @@ all-local: $(EXTRA_LIB) $(EXTRA_PROG) $(TESTS)
 # is depreciated.
 install-doc uninstall-doc:
 	@echo "Nothing to be done."
+
+# clean up files generated by tests so they can be re-run.
+build-check-clean:
+	$(RM) $(CHECK_CLEANFILES)
 
 # Run each test in order, passing $(TEST_FLAGS) to the program.
 # Since tests are done in a shell loop, "make -i" does apply inside it.
