[svn-r5489] Purpose:     Bug Fix Description:     On Linux 2.4 kernel, we need to check for Linux LFS support. There     was a failure in the Fortran code when we tried to pass a 4 byte     off_t variable to a function which expected an 8 byte off_t. This is     due to there being no check for the LFS support in the Fortran code. Solution:     Added the check for Linux LFS support. Platforms tested:     Elena will test on Linux platform...

diff --git a/fortran/configure b/fortran/configure
--- a/fortran/configure
+++ b/fortran/configure
@@ -995,6 +995,8 @@ Optional Features:
   --enable-fast-install=PKGS  optimize for fast installation default=yes
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-static-exec    Build only statically linked executables default=no
+  --enable-linux-lfs      Enable support for large (64-bit) files on Linux.
+                          [default=check]
   --enable-parallel=TYPE  Search for MPI-IO and MPI support files
 
 Optional Packages:
@@ -3882,7 +3884,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3885 "configure"' > conftest.$ac_ext
+  echo '#line 3887 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4423,7 +4425,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4426: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4428: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6234,7 +6236,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6237 "configure"
+#line 6239 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6332,7 +6334,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6335 "configure"
+#line 6337 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7234,6 +7236,119 @@ else
   LT_STATIC_EXEC=""
 fi
 
+
+case "$host_cpu-$host_vendor-$host_os" in
+  *linux*)
+                # Check whether --enable-linux-lfs or --disable-linux-lfs was given.
+if test "${enable_linux_lfs+set}" = set; then
+  enableval="$enable_linux_lfs"
+
+fi;
+
+    case "X-$enable_linux_lfs" in
+      X-yes)
+        LINUX_LFS=yes
+        ;;
+      X-no)
+        LINUX_LFS=no
+        ;;
+      X-|*)
+        LINUX_LFS=no
+
+for ac_func in getdents64
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6
+if eval "test \"\${$as_ac_var+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char $ac_func ();
+char (*f) ();
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+f = $ac_func;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+eval "$as_ac_var=no"
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_var'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_var'}'`" >&6
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+                                     LINUX_LFS=yes
+fi
+done
+
+        ;;
+    esac
+
+    echo "$as_me:$LINENO: checking for large file support on linux mode" >&5
+echo $ECHO_N "checking for large file support on linux mode... $ECHO_C" >&6
+    if test "X$LINUX_LFS" = "Xyes"; then
+      echo "$as_me:$LINENO: result: enabled" >&5
+echo "${ECHO_T}enabled" >&6
+      CPPFLAGS="-D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE $CPPFLAGS"
+    else
+      echo "$as_me:$LINENO: result: disabled" >&5
+echo "${ECHO_T}disabled" >&6
+    fi
+
+                CPPFLAGS="-D_POSIX_SOURCE $CPPFLAGS"
+
+                    CPPFLAGS="-D_BSD_SOURCE $CPPFLAGS"
+    ;;
+esac
 
 for ac_prog in f90 pgf90 f95 g95
 do
