[svn-r3298] Purpose:     Bug Fix Description:     Small bug fix to the acsite.m4 stuff. We should check if the Fortran     9X compiler was found instead of the CC compiler. Solution:     Changed CC to F9X macro. Platforms tested:     Linux

diff --git a/fortran/configure b/fortran/configure
--- a/fortran/configure
+++ b/fortran/configure
@@ -1770,7 +1770,7 @@ fi
 test -n "$F9X" && break
 done
 
-test -z "$CC" && { echo "configure: error: no acceptable f9X compiler found in \$PATH" 1>&2; exit 1; }
+test -z "$F9X" && { echo "configure: error: no acceptable f9X compiler found in \$PATH" 1>&2; exit 1; }
 
 
 echo $ac_n "checking whether the Fortran 9X compiler ($F9X $FFLAGS $LDFLAGS) works""... $ac_c" 1>&6
