[svn-r18055] Bug fix: 1192
Description:
Fixed exit code (sometimes return code in Main) to follow the HDF5 standards.

Tested:
H5committested plus serial test in Jam.

diff --git a/tools/h5jam/testh5jam.sh.in b/tools/h5jam/testh5jam.sh.in
--- a/tools/h5jam/testh5jam.sh.in
+++ b/tools/h5jam/testh5jam.sh.in
@@ -21,6 +21,10 @@ USE_FILTER_DEFLATE="@USE_FILTER_DEFLATE@"
 USE_FILTER_SHUFFLE="@USE_FILTER_SHUFFLE@"
 USE_FILTER_FLETCHER32="@USE_FILTER_FLETCHER32@"
 
+TESTNAME=h5jam/h5unjam
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 DUMPER=h5dump               # The dumper to use
 DUMPER_BIN=`pwd`/../$DUMPER    # The path of the dumper binary
 JAM=h5jam                     # Tool to test
@@ -526,7 +530,9 @@ CLEANUP tac3.h5 taj3.h5
 
 
 if test $nerrors -eq 0 ; then
-   echo "All $JAM tests passed."
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
 fi
-
-exit $nerrors
diff --git a/tools/misc/testh5repart.sh.in b/tools/misc/testh5repart.sh.in
--- a/tools/misc/testh5repart.sh.in
+++ b/tools/misc/testh5repart.sh.in
@@ -15,6 +15,10 @@
 #
 # Tests for the h5repart tool
 
+TESTNAME=h5repart
+EXIT_SUCCESS=0
+EXIT_FAILURE=1
+
 REPART=h5repart             # The tool name
 REPART_BIN=`pwd`/$REPART    # The path of the tool binary
 
@@ -100,14 +104,16 @@ TOOLTEST -m 20000 -family_to_sec2 family_file%05d.h5 $actual_dir/family_to_sec2.
 OUTPUTTEST
 echo
 
-if test $nerrors -eq 0 ; then
-   echo "All $REPART tests passed."
-fi
-
 # Clean up output file
 if test -z "$HDF5_NOCLEANUP"; then
     cd $actual_dir
     rm -f fst_family*.h5 scd_family*.h5 family_to_sec2.h5
 fi
 
-exit $nerrors
+if test $nerrors -eq 0 ; then
+    echo "All $TESTNAME tests passed."
+    exit $EXIT_SUCCESS
+else
+    echo "$TESTNAME tests failed with $nerrors errors."
+    exit $EXIT_FAILURE
+fi
