Fix errors in testh5dump.sh tests that grep for reference error messages.

diff --git a/tools/test/h5dump/testh5dump.sh.in b/tools/test/h5dump/testh5dump.sh.in
--- a/tools/test/h5dump/testh5dump.sh.in
+++ b/tools/test/h5dump/testh5dump.sh.in
@@ -935,6 +935,36 @@ GREPTEST()
     fi
 }
 
+# Call the h5dump tool and grep for an error string 
+#
+GREPERRTEST()
+{
+    expectdata=$1
+    actual=$TESTDIR/$2
+    actual_err="$TESTDIR/`basename $2 .ddl`.oerr"
+    shift
+    shift
+
+    # Run test.
+    TESTING $DUMPER -p $@
+    (
+      cd $TESTDIR
+      $ENVCMD $RUNSERIAL $DUMPER_BIN -p "$@"
+    ) >$actual 2>$actual_err
+    $GREP "$expectdata" $actual_err > /dev/null
+    if [ $? -eq 0 ]; then
+        echo " PASSED"
+    else
+        echo " FAILED"
+        nerrors="`expr $nerrors + 1`"
+    fi
+
+    # Clean up output file
+    if test -z "$HDF5_NOCLEANUP"; then
+     rm -f $actual $actual_err
+    fi
+}
+
 # Print a "SKIP" message
 SKIP() {
    TESTING $DUMPER $@
@@ -1137,7 +1167,7 @@ TOOLTEST tvlenstr_array.ddl --enable-error-stack tvlenstr_array.h5
 # test for files with array data
 TOOLTEST tarray1.ddl --enable-error-stack tarray1.h5
 # # added for bug# 2092 - tarray1_big.h
-GREPTEST "Undefined reference pointer" tarray1_big.ddl --enable-error-stack -R tarray1_big.h5
+GREPERRTEST "unable to get object address" tarray1_big.ddl --enable-error-stack -R tarray1_big.h5
 TOOLTEST tarray2.ddl --enable-error-stack tarray2.h5
 TOOLTEST tarray3.ddl --enable-error-stack tarray3.h5
 TOOLTEST tarray4.ddl --enable-error-stack tarray4.h5
@@ -1345,9 +1375,9 @@ fi
 
 # test for dataset region references
 TOOLTEST  tdatareg.ddl --enable-error-stack tdatareg.h5
-GREPTEST "Undefined reference pointer" tdataregR.ddl --enable-error-stack -R tdatareg.h5
+GREPERRTEST "unable to get object address" tdataregR.ddl --enable-error-stack -R tdatareg.h5
 TOOLTEST  tattrreg.ddl --enable-error-stack tattrreg.h5
-GREPTEST "Undefined reference pointer" tattrregR.ddl --enable-error-stack -R tattrreg.h5
+GREPERRTEST "unable to get object address" tattrregR.ddl --enable-error-stack -R tattrreg.h5
 TOOLTEST2 tbinregR.exp --enable-error-stack -d /Dataset1 -s 0 -R -y -o tbinregR.txt    tdatareg.h5
 
 # Clean up text output files
